source: https://opendata.hhs.gov/datasets/medicaid-provider-spending/

In [2]:
import pandas as pd
pd.set_option('display.max_rows', None) # no row limit
import pyarrow.dataset as ds

# below loads the data but takes ~2.5 minutes

In [3]:
# ### UNCOMMENT IN CASE YOU NEED TO RUN AGAIN ####
#
# dataset = ds.dataset(
#     "/Users/luketaylor/Desktop/Pycharm/Home_Healthcare_Spending_Trends/Datasets/medicaid-provider-spending.parquet",
#     format="parquet"
# )
# table = dataset.to_table()
# medicaid_provider_spending = table.to_pandas()
#
# medicaid_provider_spending['CLAIMS_PER_BENEFICIARY'] = medicaid_provider_spending['TOTAL_CLAIMS'] / medicaid_provider_spending['TOTAL_UNIQUE_BENEFICIARIES']
# medicaid_provider_spending['PAID_PER_CLAIM'] = medicaid_provider_spending['TOTAL_PAID'] / medicaid_provider_spending['TOTAL_CLAIMS']
# medicaid_provider_spending.head()

,BILLING_PROVIDER_NPI_NUM,SERVICING_PROVIDER_NPI_NUM,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM
0,1376609297,1376609297,T1019,2024-07,39765,1205701,1.188877e+08,30.320659,98.604609
1,1376609297,1376609297,T1019,2024-08,39677,1152534,1.155611e+08,29.047912,100.266948
2,1376609297,1376609297,T1019,2024-05,39678,1157235,1.128233e+08,29.165659,97.493815
3,1376609297,1376609297,T1019,2024-06,39834,1164582,1.114492e+08,29.235879,95.698863
4,1376609297,1376609297,T1019,2024-09,39527,1099808,1.111998e+08,27.824221,101.108405

In [4]:
print('len df:')
print(len(medicaid_provider_spending))
medicaid_provider_spending.columns

len df:
227083361

Index(['BILLING_PROVIDER_NPI_NUM', 'SERVICING_PROVIDER_NPI_NUM', 'HCPCS_CODE',
       'CLAIM_FROM_MONTH', 'TOTAL_UNIQUE_BENEFICIARIES', 'TOTAL_CLAIMS',
       'TOTAL_PAID', 'CLAIMS_PER_BENEFICIARY', 'PAID_PER_CLAIM'],
      dtype='object')

# load in hcpc options

In [5]:
hcpc_mapping_2026 = pd.read_csv('/Users/luketaylor/Desktop/Pycharm/Home_Healthcare_Spending_Trends/Datasets/2026_HCPC_Code_List.csv')
hcpc_mapping_2026.head()

  HCPCS_CODE            HCPCS_DESCRIPTION                HCPCS_CATEGORY
0      86890     Autologous blood process  CLINICAL LABORATORY SERVICES
1      86891  Autologous blood op salvage  CLINICAL LABORATORY SERVICES
2      86927          Plasma fresh frozen  CLINICAL LABORATORY SERVICES
3      86930            Frozen blood prep  CLINICAL LABORATORY SERVICES
4      86931            Frozen blood thaw  CLINICAL LABORATORY SERVICES

groupby options:
- single groupby
- df.groupby(['col_1', 'col_2']).agg({
    'col_3': 'sum',
    'col_4': 'mean'
})


- groupby multiple columns
df.groupby(['col_1', 'col_2']).agg({
    'col_3': ['sum', 'count'],
    'col_4': ['mean', 'max']
})
# takes ~30 seconds to run

In [6]:
hcpc_by_month = medicaid_provider_spending.groupby(['HCPCS_CODE', 'CLAIM_FROM_MONTH']).agg({
    'TOTAL_UNIQUE_BENEFICIARIES': 'sum',
    'TOTAL_CLAIMS': 'sum',
    'TOTAL_PAID': 'sum'
})

hcpc_by_month.reset_index(inplace=True)

hcpc_by_month['CLAIMS_PER_BENEFICIARY'] = hcpc_by_month['TOTAL_CLAIMS'] / hcpc_by_month['TOTAL_UNIQUE_BENEFICIARIES']
hcpc_by_month['PAID_PER_CLAIM'] = hcpc_by_month['TOTAL_PAID'] / hcpc_by_month['TOTAL_CLAIMS']
hcpc_by_month['PAID_PER_BENEFICIARY'] = hcpc_by_month['TOTAL_PAID'] / hcpc_by_month['TOTAL_UNIQUE_BENEFICIARIES']
hcpc_by_month.head()

,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM,PAID_PER_BENEFICIARY
0,-,2018-01,15,19,0.0,1.266667,0.0,0.0
1,-,2018-02,14,19,0.0,1.357143,0.0,0.0
2,-,2018-03,15,23,0.0,1.533333,0.0,0.0
3,0,2020-08,22,22,0.0,1.000000,0.0,0.0
4,0,2021-01,90,105,0.0,1.166667,0.0,0.0

In [7]:
hcpc_mapping_2026.head()

  HCPCS_CODE            HCPCS_DESCRIPTION                HCPCS_CATEGORY
0      86890     Autologous blood process  CLINICAL LABORATORY SERVICES
1      86891  Autologous blood op salvage  CLINICAL LABORATORY SERVICES
2      86927          Plasma fresh frozen  CLINICAL LABORATORY SERVICES
3      86930            Frozen blood prep  CLINICAL LABORATORY SERVICES
4      86931            Frozen blood thaw  CLINICAL LABORATORY SERVICES

# try and join to bring in descriptions

In [8]:
hcpc_w_descript_by_month = hcpc_by_month.merge(hcpc_mapping_2026, how='left', on=['HCPCS_CODE'])
hcpc_w_descript_by_month=hcpc_w_descript_by_month[['HCPCS_CATEGORY','HCPCS_DESCRIPTION','HCPCS_CODE', 'CLAIM_FROM_MONTH','TOTAL_UNIQUE_BENEFICIARIES','TOTAL_CLAIMS','TOTAL_PAID','CLAIMS_PER_BENEFICIARY','PAID_PER_CLAIM']]
hcpc_w_descript_by_month.head(100)

,HCPCS_CATEGORY,HCPCS_DESCRIPTION,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM
0,NaN,NaN,-,2018-01,15,19,0.00,1.266667,0.000000
1,NaN,NaN,-,2018-02,14,19,0.00,1.357143,0.000000
2,NaN,NaN,-,2018-03,15,23,0.00,1.533333,0.000000
3,NaN,NaN,0,2020-08,22,22,0.00,1.000000,0.000000
4,NaN,NaN,0,2021-01,90,105,0.00,1.166667,0.000000
5,NaN,NaN,0,2021-02,47,48,0.00,1.021277,0.000000
6,NaN,NaN,0,2021-03,108,115,0.00,1.064815,0.000000
7,NaN,NaN,0,2021-04,47,50,0.00,1.063830,0.000000
8,NaN,NaN,0000,2018-04,28,37,0.00,1.321429,0.000000
9,NaN,NaN,0000,2019-03,13,117,0.00,9.000000,0.000000
10,NaN,NaN,0000,2019-05,14,101,0.00,7.214286,0.000000
11,NaN,NaN,0000,2019-06,15,118,0.00,7.866667,0.000000
12,NaN,NaN,00000,2018-01,27,51,0.00,1.888889,0.000000
13,NaN,NaN,00000,2018-02,12,17,0.00,1.416667,0.000000
14,NaN,NaN,00000,2018-03,17,17,444.21,1.000000,26.130000
15,NaN,NaN,00000,2018-05,226,917,23909.42,4.057522,26.073522
16,NaN,NaN,00000,2018-06,19,20,554.94,1.052632,27.747000
17,NaN,NaN,00000,2018-07,12,12,313.56,1.000000,26.130000
18,NaN,NaN,00000,2018-08,19,20,554.94,1.052632,27.747000
19,NaN,NaN,00000,2018-10,25,47,0.00,1.880000,0.000000
20,NaN,NaN,00000,2018-11,69,128,1479.33,1.855072,11.557266
21,NaN,NaN,00000,2019-01,55,166,1414.65,3.018182,8.521988
22,NaN,NaN,00000,2019-02,42,74,1167.06,1.761905,15.771081
23,NaN,NaN,00000,2019-03,33,157,716.64,4.757576,4.564586
24,NaN,NaN,00000,2019-04,38,102,1237.95,2.684211,12.136765
25,NaN,NaN,00000,2019-05,53,108,1265.37,2.037736,11.716389
26,NaN,NaN,00000,2019-06,25,77,313.56,3.080000,4.072208
27,NaN,NaN,00000,2019-07,14,64,0.00,4.571429,0.000000
28,NaN,NaN,00000,2019-08,57,185,444.21,3.245614,2.401135
29,NaN,NaN,00000,2019-09,63,227,0.00,3.603175,0.000000
30,NaN,NaN,00000,2019-10,77,234,339.69,3.038961,1.451667
31,NaN,NaN,00000,2019-11,155,584,372.03,3.767742,0.637038
32,NaN,NaN,00000,2019-12,321,866,0.00,2.697819,0.000000
33,NaN,NaN,00000,2020-01,403,1102,391.95,2.734491,0.355672
34,NaN,NaN,00000,2020-02,334,1127,0.00,3.374251,0.000000
35,NaN,NaN,00000,2020-03,297,894,0.00,3.010101,0.000000
36,NaN,NaN,00000,2020-04,196,517,0.00,2.637755,0.000000
37,NaN,NaN,00000,2020-05,193,548,0.00,2.839378,0.000000
38,NaN,NaN,00000,2020-06,256,806,365.82,3.148438,0.453871
39,NaN,NaN,00000,2020-07,257,763,0.00,2.968872,0.000000
40,NaN,NaN,00000,2020-08,230,561,0.00,2.439130,0.000000
41,NaN,NaN,00000,2020-09,218,710,0.00,3.256881,0.000000
42,NaN,NaN,00000,2020-10,235,567,1403.52,2.412766,2.475344
43,NaN,NaN,00000,2020-11,160,396,0.00,2.475000,0.000000
44,NaN,NaN,00000,2020-12,138,335,0.00,2.427536,0.000000
45,NaN,NaN,00000,2021-01,254,432,1724.59,1.700787,3.992106
46,NaN,NaN,00000,2021-02,162,298,651.96,1.839506,2.187785
47,NaN,NaN,00000,2021-03,216,487,0.00,2.254630,0.000000
48,NaN,NaN,00000,2021-04,194,478,0.00,2.463918,0.000000
49,NaN,NaN,00000,2021-05,189,604,0.00,3.195767,0.000000
50,NaN,NaN,00000,2021-06,192,665,0.00,3.463542,0.000000
51,NaN,NaN,00000,2021-07,245,713,573.57,2.910204,0.804446
52,NaN,NaN,00000,2021-08,180,587,0.00,3.261111,0.000000
53,NaN,NaN,00000,2021-09,193,601,0.00,3.113990,0.000000
54,NaN,NaN,00000,2021-10,173,567,0.00,3.277457,0.000000
55,NaN,NaN,00000,2021-11,103,446,0.00,4.330097,0.000000
56,NaN,NaN,00000,2021-12,85,641,0.00,7.541176,0.000000
57,NaN,NaN,00000,2022-01,121,159,0.00,1.314050,0.000000
58,NaN,NaN,00000,2022-09,83,91,0.00,1.096386,0.000000
59,NaN,NaN,00000,2022-10,19,21,0.00,1.105263,0.000000
60,NaN,NaN,00000,2022-11,66,72,0.00,1.090909,0.000000
61,NaN,NaN,00000,2022-12,40,58,0.00,1.450000,0.000000
62,NaN,NaN,00000,2023-01,32,32,13080.00,1.000000,408.750000
63,NaN,NaN,00000,2023-02,27,41,8502.00,1.518519,207.365854
64,NaN,NaN,00000,2023-04,12,15,0.00,1.250000,0.000000
65,NaN,NaN,00000,2023-05,28,31,0.00,1.107143,0.000000
66,NaN,NaN,00000,2023-06,25,32,0.00,1.280000,0.000000
67,NaN,NaN,00000,2023-07,28,31,0.00,1.107143,0.000000
68,NaN,NaN,00000,2023-08,143,194,0.00,1.356643,0.000000
69,NaN,NaN,00000,2023-09,151,218,0.00,1.443709,0.000000
70,NaN,NaN,00000,2023-10,99,134,0.00,1.353535,0.000000
71,NaN,NaN,00000,2023-11,132,155,339.69,1.174242,2.191548
72,NaN,NaN,00000,2023-12,212,247,0.00,1.165094,0.000000
73,NaN,NaN,00000,2024-01,746,1049,0.00,1.406166,0.000000
74,NaN,NaN,00000,2024-02,994,1517,0.00,1.526157,0.000000
75,NaN,NaN,00000,2024-03,1675,2654,0.00,1.584478,0.000000
76,NaN,NaN,00000,2024-04,2554,4188,0.00,1.639781,0.000000
77,NaN,NaN,00000,2024-05,3542,5782,418.08,1.632411,0.072307
78,NaN,NaN,00000,2024-06,3180,4897,0.00,1.539937,0.000000
79,NaN,NaN,00000,2024-07,3214,4986,0.00,1.551338,0.000000
80,NaN,NaN,00000,2024-08,2727,3981,0.00,1.459846,0.000000
81,NaN,NaN,00000,2024-09,2006,2575,0.00,1.283649,0.000000
82,NaN,NaN,00000,2024-10,1312,1548,0.00,1.179878,0.000000
83,NaN,NaN,00000,2024-11,211,220,0.00,1.042654,0.000000
84,NaN,NaN,0000000,2018-01,91,201,7472.82,2.208791,37.178209
85,NaN,NaN,0000000,2018-02,93,181,5488.75,1.946237,30.324586
86,NaN,NaN,0000000,2018-03,117,235,14171.78,2.008547,60.305447
87,NaN,NaN,0000000,2018-04,86,180,9655.56,2.093023,53.642000
88,NaN,NaN,0000000,2018-05,91,181,6139.98,1.989011,33.922541
89,NaN,NaN,0000000,2018-06,18,35,1187.43,1.944444,33.926571
90,NaN,NaN,0000000,2018-08,25,49,3981.55,1.960000,81.256122
91,NaN,NaN,00001,2018-10,17,17,0.00,1.000000,0.000000
92,NaN,NaN,00001,2019-08,30,35,0.00,1.166667,0.000000
93,NaN,NaN,00001,2019-09,83,87,0.00,1.048193,0.000000
94,NaN,NaN,00001,2019-10,44,54,0.00,1.227273,0.000000
95,NaN,NaN,00001,2019-11,32,36,0.00,1.125000,0.000000
96,NaN,NaN,00001,2019-12,29,34,0.00,1.172414,0.000000
97,NaN,NaN,00001,2020-01,20,23,0.00,1.150000,0.000000
98,NaN,NaN,00001,2020-02,19,23,0.00,1.210526,0.000000
99,NaN,NaN,00001,2020-03,20,22,0.00,1.100000,0.000000

# Look into Home health type CPT codes
- HCPCS = T10**
- https://www.aapc.com/codes/hcpcs-codes-range/409/?srsltid=AfmBOoqCW_2RgDV_1TvqDTG2nLd2tqO9m5DzuXbDOXY4h3rCvKfV_MXI


### output
- one random month's worth of HCPC codes billed
    - verify the ranks are working as intended

In [9]:
# home_health_util = hcpc_by_month_filtered = hcpc_by_month[hcpc_by_month['HCPCS_CODE'].str[:3] == 'T10']
home_health_util = hcpc_by_month[hcpc_by_month['HCPCS_CODE'].str[:3] == 'T10']

# Sort the DataFrame by Category and Sales (descending)
# Sorting first ensures ranks are assigned correctly within groups
home_health_util_sorted = home_health_util.sort_values(['HCPCS_CODE', 'CLAIM_FROM_MONTH'], ascending=[True, False])

# Apply the rank function within each group
# method='min' is similar to SQL's RANK(), which leaves gaps after ties
home_health_util_sorted['PAID_MONTHLY_RANK'] = home_health_util_sorted.groupby('CLAIM_FROM_MONTH')['TOTAL_PAID'].rank(method='min', ascending=False)
home_health_util_sorted['BENEFICIARIES_MONTHLY_RANK'] = home_health_util_sorted.groupby('CLAIM_FROM_MONTH')['TOTAL_UNIQUE_BENEFICIARIES'].rank(method='min', ascending=False)
home_health_util_sorted['CLAIMS_MONTHLY_RANK'] = home_health_util_sorted.groupby('CLAIM_FROM_MONTH')['TOTAL_CLAIMS'].rank(method='min', ascending=False)
display(home_health_util_sorted[home_health_util_sorted.CLAIM_FROM_MONTH=='2021-09'])
# home_health_util_sorted.head()

,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM,PAID_PER_BENEFICIARY,PAID_MONTHLY_RANK,BENEFICIARIES_MONTHLY_RANK,CLAIMS_MONTHLY_RANK
503067,T1000,2021-09,11150,252530,1.036551e+08,22.648430,410.466562,9296.423389,4.0,19.0,8.0
503151,T1001,2021-09,89206,138044,6.214714e+06,1.547474,45.019804,69.666993,16.0,5.0,13.0
503191,T10019,2021-09,12,14,0.000000e+00,1.166667,0.000000,0.000000,32.0,32.0,32.0
503236,T1002,2021-09,70406,149808,1.742939e+07,2.127773,116.344844,247.555442,11.0,7.0,11.0
503320,T1003,2021-09,25625,141263,2.863729e+07,5.512702,202.723204,1117.552700,8.0,13.0,12.0
503404,T1004,2021-09,9363,151073,7.292299e+06,16.135106,48.270034,778.842124,14.0,20.0,10.0
503488,T1005,2021-09,27745,306849,1.864946e+07,11.059614,60.777325,672.173779,10.0,12.0,7.0
503572,T1006,2021-09,85,329,6.496138e+04,3.870588,197.451003,764.251529,29.0,29.0,29.0
503656,T1007,2021-09,7707,8843,6.847426e+05,1.147398,77.433296,88.846846,23.0,21.0,25.0
503727,T1009,2021-09,13,51,1.330836e+04,3.923077,260.948235,1023.720000,31.0,31.0,30.0
503809,T1012,2021-09,2456,9069,4.994760e+05,3.692590,55.075090,203.369703,26.0,25.0,24.0
503893,T1013,2021-09,49649,80735,4.327438e+06,1.626115,53.600520,87.160628,20.0,10.0,15.0
503977,T1014,2021-09,13863,24462,1.698745e+05,1.764553,6.944424,12.253806,28.0,16.0,21.0
504061,T1015,2021-09,3406502,4709557,6.825883e+08,1.382520,144.936835,200.378068,2.0,1.0,2.0
504145,T1016,2021-09,421497,1154800,6.367166e+07,2.739759,55.136529,151.060776,6.0,3.0,3.0
504231,T1017,2021-09,354860,878063,8.998836e+07,2.474393,102.485088,253.588357,5.0,4.0,4.0
504315,T1018,2021-09,73218,478446,2.754447e+07,6.534541,57.570701,376.198086,9.0,6.0,5.0
504399,T1019,2021-09,681126,13690418,1.456202e+09,20.099685,106.366539,2137.933927,1.0,2.0,1.0
504491,T1020,2021-09,64640,412623,1.070136e+08,6.383400,259.349652,1655.532666,3.0,8.0,6.0
504575,T1021,2021-09,5682,78522,3.826751e+06,13.819430,48.734765,673.486663,21.0,23.0,16.0
504659,T1022,2021-09,487,3891,6.753309e+05,7.989733,173.562292,1386.716386,24.0,28.0,28.0
504743,T1023,2021-09,23386,28293,5.988661e+06,1.209826,211.665804,256.078876,17.0,14.0,19.0
504828,T1024,2021-09,11333,25937,5.616422e+06,2.288626,216.540940,495.581255,18.0,18.0,20.0
504912,T1025,2021-09,3321,43449,6.517657e+06,13.083107,150.007060,1962.558494,15.0,24.0,18.0
504996,T1026,2021-09,1509,12129,2.716932e+06,8.037773,224.002948,1800.484930,22.0,26.0,23.0
505080,T1027,2021-09,37574,113878,1.085727e+07,3.030766,95.341249,288.957012,13.0,11.0,14.0
505164,T1028,2021-09,5743,6828,5.058322e+05,1.188926,74.082045,88.078043,25.0,22.0,27.0
505220,T1029,2021-09,23,31,2.088000e+04,1.347826,673.548387,907.826087,30.0,30.0,31.0
505303,T1030,2021-09,13653,48735,5.461031e+06,3.569545,112.055627,399.987620,19.0,17.0,17.0
505387,T1031,2021-09,1412,8301,4.698316e+05,5.878895,56.599393,332.741898,27.0,27.0,26.0
505493,T1040,2021-09,60010,231164,4.918234e+07,3.852091,212.759530,819.569140,7.0,9.0,9.0
505577,T1041,2021-09,15620,15622,1.384561e+07,1.000128,886.289015,886.402496,12.0,15.0,22.0

# check to filter on a given month to verify HCPCs percentile logic is working
- to streamline spot checking, filter what you want to see
    - i want to look one 'dimension' of data
    - reduce a variable, reduce the "noise"
    - the more noise you remove, the quicker you can check that the percentile logic is working
    - quicker (and repeatable**) validation
- I want to see how a HCPC claim count(#)/cost($)/beneficiaries(~human lives~) stacks up amongst others in the given month
        - I want to see how
- my data is aggregated by groups by columns, there are aggregations based on one of 3 columns:
    - TOTAL_CLAIMS
    - TOTAL_PAID
    - TOTAL_UNIQUE_BENEFICIARIES

# reset dataframe(s) here

In [11]:
min_clm_mnth = home_health_util_sorted['CLAIM_FROM_MONTH'].min()
# invg_cols = home_health_util_sorted.filter(like='TOTAL_CLAIMS').columns
invg_cols = ['TOTAL_CLAIMS','CLAIMS_MONTHLY_RANK']
print(invg_cols)

# at minimum should have these columns
#   this gives context to what you're looking into
base_cols = home_health_util_sorted[['HCPCS_CODE','CLAIM_FROM_MONTH']].columns


df_filtered_to_month = home_health_util_sorted[home_health_util_sorted.CLAIM_FROM_MONTH==min_clm_mnth]

# # create a list of columns with 'MONTH_PCTILE' as part of the column name
pctile_cols = home_health_util_sorted.filter(like='MONTH_PCTILE').columns
remaining_cols = home_health_util_sorted.columns.difference(pctile_cols)

final_cols = base_cols.to_list() + invg_cols#.to_list()

# add layer of context
#   divide by percentile to give depth of records, if they are big chunks -> fewer rows of data
#   one less thing to think about
# since we've filtered down its easier to add a column based on one MAX
#   # no need to account for a group by
#   # efficient code

second_dimension_filtered_df = df_filtered_to_month[final_cols].copy()
invg_max_rank = second_dimension_filtered_df.CLAIMS_MONTHLY_RANK.max() ## hardocded right now, need to add flexibility in case a new level of depth gets added above

second_dimension_filtered_df['CLAIMS_MONTHLY_PCTILE'] = second_dimension_filtered_df['CLAIMS_MONTHLY_RANK'] / invg_max_rank
## include max pctile, why not
#   not as impactful of an addition(i don't like having a column of all the same value, too much "noise" IMO when reviewing data

display(second_dimension_filtered_df)
# T1019 has the most claims out of all other HCPCs codes for this month

['TOTAL_CLAIMS', 'CLAIMS_MONTHLY_RANK']

,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_CLAIMS,CLAIMS_MONTHLY_RANK,CLAIMS_MONTHLY_PCTILE
503023,T1000,2018-01,127379,11.0,0.354839
503107,T1001,2018-01,128071,10.0,0.322581
503192,T1002,2018-01,176961,7.0,0.225806
503276,T1003,2018-01,124026,14.0,0.451613
503360,T1004,2018-01,124627,12.0,0.387097
503444,T1005,2018-01,108562,16.0,0.516129
503528,T1006,2018-01,501,29.0,0.935484
503612,T1007,2018-01,3941,26.0,0.838710
503696,T1009,2018-01,430,30.0,0.967742
503765,T1012,2018-01,4425,25.0,0.806452
503849,T1013,2018-01,117585,15.0,0.483871
503933,T1014,2018-01,2133,28.0,0.903226
504017,T1015,2018-01,3447849,2.0,0.064516
504101,T1016,2018-01,1225820,3.0,0.096774
504187,T1017,2018-01,647614,5.0,0.161290
504271,T1018,2018-01,573842,6.0,0.193548
504355,T1019,2018-01,9047566,1.0,0.032258
504447,T1020,2018-01,695037,4.0,0.129032
504531,T1021,2018-01,124536,13.0,0.419355
504615,T1022,2018-01,9341,21.0,0.677419
504699,T1023,2018-01,31581,18.0,0.580645
504784,T1024,2018-01,29925,20.0,0.645161
504868,T1025,2018-01,38337,17.0,0.548387
504952,T1026,2018-01,6112,23.0,0.741935
505036,T1027,2018-01,145886,9.0,0.290323
505120,T1028,2018-01,6482,22.0,0.709677
505204,T1029,2018-01,34,31.0,1.000000
505259,T1030,2018-01,29949,19.0,0.612903
505343,T1031,2018-01,2767,27.0,0.870968
505449,T1040,2018-01,169576,8.0,0.258065
505533,T1041,2018-01,6053,24.0,0.774194

# output filtered to top percentiles
- write investigative code and production level code `second_dimension_filtered_df
    - investigative : 'hey could you look into X/Y/Z'
    - start there, production-ize to easily iterate across all A-Z
        - that's production code

# TO-DO:
    - average by 2/3 percentiles, see if there's one that is stronger in amount per claimant
    - curiosity

In [12]:
# pull 'base_cols' list from the above code
home_health_util_sorted['PAID_MAX_MONTHLY_RANK'] = (
    home_health_util_sorted.groupby('CLAIM_FROM_MONTH')['PAID_MONTHLY_RANK']
      .transform('max')
)

home_health_util_sorted['BENEFICIARIES_MAX_MONTHLY_RANK'] = (
    home_health_util_sorted.groupby('CLAIM_FROM_MONTH')['BENEFICIARIES_MONTHLY_RANK']
      .transform('max')
)

home_health_util_sorted['CLAIMS_MAX_MONTHLY_RANK'] = (
    home_health_util_sorted.groupby('CLAIM_FROM_MONTH')['CLAIMS_MONTHLY_RANK']
      .transform('max')
)

# changed this from MR to MONTH
home_health_util_sorted['PAID_MONTH_PCTILE'] = home_health_util_sorted['PAID_MONTHLY_RANK'] / home_health_util_sorted['PAID_MAX_MONTHLY_RANK']
home_health_util_sorted['BENEFICIARIES_MONTH_PCTILE'] = home_health_util_sorted['BENEFICIARIES_MONTHLY_RANK'] / home_health_util_sorted['BENEFICIARIES_MAX_MONTHLY_RANK']
home_health_util_sorted['CLAIMS_MONTH_PCTILE'] = home_health_util_sorted['CLAIMS_MONTHLY_RANK'] / home_health_util_sorted['CLAIMS_MAX_MONTHLY_RANK']

home_health_util_sorted['PAID_PER_BENEFICIARY'] = home_health_util_sorted['TOTAL_PAID'] / home_health_util_sorted['TOTAL_UNIQUE_BENEFICIARIES']


display(home_health_util_sorted[home_health_util_sorted['CLAIM_FROM_MONTH']=='2021-09'])

,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM,PAID_PER_BENEFICIARY,PAID_MONTHLY_RANK,BENEFICIARIES_MONTHLY_RANK,CLAIMS_MONTHLY_RANK,PAID_MAX_MONTHLY_RANK,BENEFICIARIES_MAX_MONTHLY_RANK,CLAIMS_MAX_MONTHLY_RANK,PAID_MONTH_PCTILE,BENEFICIARIES_MONTH_PCTILE,CLAIMS_MONTH_PCTILE
503067,T1000,2021-09,11150,252530,1.036551e+08,22.648430,410.466562,9296.423389,4.0,19.0,8.0,32.0,32.0,32.0,0.12500,0.59375,0.25000
503151,T1001,2021-09,89206,138044,6.214055e+06,1.547474,45.015030,69.659606,16.0,5.0,13.0,32.0,32.0,32.0,0.50000,0.15625,0.40625
503191,T10019,2021-09,12,14,0.000000e+00,1.166667,0.000000,0.000000,32.0,32.0,32.0,32.0,32.0,32.0,1.00000,1.00000,1.00000
503236,T1002,2021-09,70406,149808,1.742939e+07,2.127773,116.344844,247.555442,11.0,7.0,11.0,32.0,32.0,32.0,0.34375,0.21875,0.34375
503320,T1003,2021-09,25625,141263,2.863729e+07,5.512702,202.723204,1117.552700,8.0,13.0,12.0,32.0,32.0,32.0,0.25000,0.40625,0.37500
503404,T1004,2021-09,9363,151073,7.292299e+06,16.135106,48.270034,778.842124,14.0,20.0,10.0,32.0,32.0,32.0,0.43750,0.62500,0.31250
503488,T1005,2021-09,27745,306849,1.864946e+07,11.059614,60.777325,672.173779,10.0,12.0,7.0,32.0,32.0,32.0,0.31250,0.37500,0.21875
503572,T1006,2021-09,85,329,6.496138e+04,3.870588,197.451003,764.251529,29.0,29.0,29.0,32.0,32.0,32.0,0.90625,0.90625,0.90625
503656,T1007,2021-09,7707,8843,6.847426e+05,1.147398,77.433296,88.846846,23.0,21.0,25.0,32.0,32.0,32.0,0.71875,0.65625,0.78125
503727,T1009,2021-09,13,51,1.330836e+04,3.923077,260.948235,1023.720000,31.0,31.0,30.0,32.0,32.0,32.0,0.96875,0.96875,0.93750
503809,T1012,2021-09,2456,9069,4.994760e+05,3.692590,55.075090,203.369703,26.0,25.0,24.0,32.0,32.0,32.0,0.81250,0.78125,0.75000
503893,T1013,2021-09,49649,80735,4.327438e+06,1.626115,53.600520,87.160628,20.0,10.0,15.0,32.0,32.0,32.0,0.62500,0.31250,0.46875
503977,T1014,2021-09,13863,24462,1.698745e+05,1.764553,6.944424,12.253806,28.0,16.0,21.0,32.0,32.0,32.0,0.87500,0.50000,0.65625
504061,T1015,2021-09,3406502,4709557,6.825883e+08,1.382520,144.936835,200.378068,2.0,1.0,2.0,32.0,32.0,32.0,0.06250,0.03125,0.06250
504145,T1016,2021-09,421497,1154800,6.367166e+07,2.739759,55.136529,151.060776,6.0,3.0,3.0,32.0,32.0,32.0,0.18750,0.09375,0.09375
504231,T1017,2021-09,354860,878063,8.998836e+07,2.474393,102.485088,253.588357,5.0,4.0,4.0,32.0,32.0,32.0,0.15625,0.12500,0.12500
504315,T1018,2021-09,73218,478446,2.754447e+07,6.534541,57.570701,376.198086,9.0,6.0,5.0,32.0,32.0,32.0,0.28125,0.18750,0.15625
504399,T1019,2021-09,681126,13690418,1.456202e+09,20.099685,106.366539,2137.933927,1.0,2.0,1.0,32.0,32.0,32.0,0.03125,0.06250,0.03125
504491,T1020,2021-09,64640,412623,1.070136e+08,6.383400,259.349652,1655.532666,3.0,8.0,6.0,32.0,32.0,32.0,0.09375,0.25000,0.18750
504575,T1021,2021-09,5682,78522,3.826751e+06,13.819430,48.734765,673.486663,21.0,23.0,16.0,32.0,32.0,32.0,0.65625,0.71875,0.50000
504659,T1022,2021-09,487,3891,6.753309e+05,7.989733,173.562292,1386.716386,24.0,28.0,28.0,32.0,32.0,32.0,0.75000,0.87500,0.87500
504743,T1023,2021-09,23386,28293,5.988661e+06,1.209826,211.665804,256.078876,17.0,14.0,19.0,32.0,32.0,32.0,0.53125,0.43750,0.59375
504828,T1024,2021-09,11333,25937,5.616422e+06,2.288626,216.540940,495.581255,18.0,18.0,20.0,32.0,32.0,32.0,0.56250,0.56250,0.62500
504912,T1025,2021-09,3321,43449,6.517657e+06,13.083107,150.007060,1962.558494,15.0,24.0,18.0,32.0,32.0,32.0,0.46875,0.75000,0.56250
504996,T1026,2021-09,1509,12129,2.716932e+06,8.037773,224.002948,1800.484930,22.0,26.0,23.0,32.0,32.0,32.0,0.68750,0.81250,0.71875
505080,T1027,2021-09,37574,113878,1.085727e+07,3.030766,95.341249,288.957012,13.0,11.0,14.0,32.0,32.0,32.0,0.40625,0.34375,0.43750
505164,T1028,2021-09,5743,6828,5.058322e+05,1.188926,74.082045,88.078043,25.0,22.0,27.0,32.0,32.0,32.0,0.78125,0.68750,0.84375
505220,T1029,2021-09,23,31,2.088000e+04,1.347826,673.548387,907.826087,30.0,30.0,31.0,32.0,32.0,32.0,0.93750,0.93750,0.96875
505303,T1030,2021-09,13653,48735,5.461031e+06,3.569545,112.055627,399.987620,19.0,17.0,17.0,32.0,32.0,32.0,0.59375,0.53125,0.53125
505387,T1031,2021-09,1412,8301,4.698316e+05,5.878895,56.599393,332.741898,27.0,27.0,26.0,32.0,32.0,32.0,0.84375,0.84375,0.81250
505493,T1040,2021-09,60010,231164,4.918234e+07,3.852091,212.759530,819.569140,7.0,9.0,9.0,32.0,32.0,32.0,0.21875,0.28125,0.28125
505577,T1041,2021-09,15620,15622,1.384561e+07,1.000128,886.289015,886.402496,12.0,15.0,22.0,32.0,32.0,32.0,0.37500,0.46875,0.68750

# FLAG A DIGGING POINT
## oh crap i forgot what i was doing, how do i retrack
## be an interdimensional thinker
## step back

check next section
- do the [outputs] look correct?
- As of (2/14/26)  the cell below is
    - averaging the 3 column percentiles
        -   paid / claim count / people
    - filtering
        - percentile < 0.09
        - means the HCPC is in the top 10% of every metric, ranked by most (1) to least (999)
        - if 100 people race 3 times and
                - Jerry comes in 7th, 5th, 3rd
                - Raquel comes in 1st, 75th, 49th
                - which outcome is [preferred]?
                        - to your company?
                        - to your client?
                    - both outcomes can have desirability within them, depending on what you want
                            - maybe you need to find out what caused Raquel to come in 1st

# (TO-DO): to add more context / adaptability
- look at top HCPCs regardless of month
- i just so happened to stumble upon home health
    - i can figure out context enough from google

In [17]:
pctile_cols = home_health_util_sorted.filter(like='MONTH_PCTILE').columns
# month_rank_cols = home_health_util_sorted.filter(like='MONTHLY_RANK').columns

month_rank_cols = ['PAID_MONTHLY_RANK', 'BENEFICIARIES_MONTHLY_RANK', 'CLAIMS_MONTHLY_RANK']
print(pctile_cols)
print(month_rank_cols)

Index(['PAID_MONTH_PCTILE', 'BENEFICIARIES_MONTH_PCTILE',
       'CLAIMS_MONTH_PCTILE'],
      dtype='object')
['PAID_MONTHLY_RANK', 'BENEFICIARIES_MONTHLY_RANK', 'CLAIMS_MONTHLY_RANK']

# todo:
- omit some of the builder columns
- less noise

In [232]:
max_mo = home_health_util_sorted['CLAIM_FROM_MONTH'].max()
min_mo = home_health_util_sorted['CLAIM_FROM_MONTH'].min()
# print(max_mo)
# print(min_mo)

home_health_util_sorted[(home_health_util_sorted.CLAIM_FROM_MONTH == min_mo) | (home_health_util_sorted.CLAIM_FROM_MONTH == max_mo)]

,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM,PAID_MONTHLY_RANK,BENEFICIARIES_MONTHLY_RANK,CLAIMS_MONTHLY_RANK,PAID_MAX_MONTHLY_RANK,BENEFICIARIES_MAX_MONTHLY_RANK,CLAIMS_MAX_MONTHLY_RANK,PAID_MONTH_PCTILE,BENEFICIARIES_MONTH_PCTILE,CLAIMS_MONTH_PCTILE,PAID_PER_BENEFICIARY,MONTH_PCTILE_AVG,MONTH_RANK_AVG
4322,T1000,2024-12,7805,88589,4.570321e+07,11.350288,515.901673,3.0,12.0,7.0,31.0,31.0,31.0,0.096774,0.387097,0.225806,5855.632712,0.236559,7.333333
5044,T1000,2018-01,5809,127379,3.855342e+07,21.927871,302.666979,6.0,20.0,11.0,31.0,31.0,31.0,0.193548,0.645161,0.354839,6636.842333,0.397849,12.333333
43302,T1001,2024-12,22778,34340,1.949928e+06,1.507595,56.782993,15.0,7.0,11.0,31.0,31.0,31.0,0.483871,0.225806,0.354839,85.605759,0.354839,11.000000
22830,T1001,2018-01,74921,128071,6.116320e+06,1.709414,47.757259,15.0,5.0,10.0,31.0,31.0,31.0,0.483871,0.161290,0.322581,81.636923,0.322581,10.000000
27681,T1002,2024-12,21446,46032,4.412512e+06,2.146414,95.857485,11.0,8.0,10.0,31.0,31.0,31.0,0.354839,0.258065,0.322581,205.749872,0.311828,9.666667
14707,T1002,2018-01,72190,176961,1.146929e+07,2.451323,64.812509,11.0,6.0,7.0,31.0,31.0,31.0,0.354839,0.193548,0.225806,158.876388,0.258065,8.000000
14011,T1003,2024-12,8224,31935,1.228810e+07,3.883147,384.784580,8.0,11.0,13.0,31.0,31.0,31.0,0.258065,0.354839,0.419355,1494.175044,0.344086,10.666667
10086,T1003,2018-01,20853,124026,1.880108e+07,5.947633,151.589845,9.0,13.0,14.0,31.0,31.0,31.0,0.290323,0.419355,0.451613,901.600833,0.387097,12.000000
29262,T1004,2024-12,7035,52332,3.996283e+06,7.438806,76.364044,12.0,13.0,9.0,31.0,31.0,31.0,0.387097,0.419355,0.290323,568.057305,0.365591,11.333333
30383,T1004,2018-01,8129,124627,3.731837e+06,15.331160,29.944049,19.0,16.0,12.0,31.0,31.0,31.0,0.612903,0.516129,0.387097,459.077001,0.505376,15.666667
14204,T1005,2024-12,25105,170750,1.204890e+07,6.801434,70.564561,9.0,6.0,5.0,31.0,31.0,31.0,0.290323,0.193548,0.161290,479.940205,0.215054,6.666667
14766,T1005,2018-01,19267,108562,1.140798e+07,5.634608,105.082603,12.0,14.0,16.0,31.0,31.0,31.0,0.387097,0.451613,0.516129,592.099316,0.451613,14.000000
323342,T1006,2024-12,44,63,7.779890e+03,1.431818,123.490317,29.0,29.0,28.0,31.0,31.0,31.0,0.935484,0.935484,0.903226,176.815682,0.924731,28.666667
204448,T1006,2018-01,117,501,5.219275e+04,4.282051,104.177146,27.0,29.0,29.0,31.0,31.0,31.0,0.870968,0.935484,0.935484,446.091880,0.913978,28.333333
118654,T1007,2024-12,2356,2387,2.507592e+05,1.013158,105.052040,24.0,20.0,25.0,31.0,31.0,31.0,0.774194,0.645161,0.806452,106.434304,0.741935,23.000000
145387,T1007,2018-01,2256,3941,1.468748e+05,1.746897,37.268396,26.0,23.0,26.0,31.0,31.0,31.0,0.838710,0.741935,0.838710,65.104056,0.806452,25.000000
233715,T1009,2018-01,21,430,3.203500e+04,20.476190,74.500000,29.0,31.0,30.0,31.0,31.0,31.0,0.935484,1.000000,0.967742,1525.476190,0.967742,30.000000
103212,T1012,2024-12,1323,4462,3.439999e+05,3.372638,77.095446,23.0,24.0,21.0,31.0,31.0,31.0,0.741935,0.774194,0.677419,260.015026,0.731183,22.666667
102921,T1012,2018-01,1548,4425,3.460969e+05,2.858527,78.213984,25.0,24.0,25.0,31.0,31.0,31.0,0.806452,0.774194,0.806452,223.576796,0.795699,24.666667
51918,T1013,2024-12,20095,25675,1.407222e+06,1.277681,54.809018,16.0,9.0,15.0,31.0,31.0,31.0,0.516129,0.290323,0.483871,70.028442,0.430108,13.333333
36964,T1013,2018-01,69727,117585,2.620998e+06,1.686363,22.290237,20.0,8.0,15.0,31.0,31.0,31.0,0.645161,0.258065,0.483871,37.589420,0.462366,14.333333
308844,T1014,2024-12,791,905,9.848570e+03,1.144121,10.882398,28.0,26.0,26.0,31.0,31.0,31.0,0.903226,0.838710,0.838710,12.450784,0.860215,26.666667
314060,T1014,2018-01,1341,2133,9.055130e+03,1.590604,4.245256,30.0,25.0,28.0,31.0,31.0,31.0,0.967742,0.806452,0.903226,6.752521,0.892473,27.666667
488,T1015,2024-12,1216414,1468053,2.924467e+08,1.206870,199.207195,2.0,1.0,2.0,31.0,31.0,31.0,0.064516,0.032258,0.064516,240.417095,0.053763,1.666667
238,T1015,2018-01,2486875,3447849,4.599622e+08,1.386418,133.405543,2.0,1.0,2.0,31.0,31.0,31.0,0.064516,0.032258,0.064516,184.955885,0.053763,1.666667
13357,T1016,2024-12,97209,177090,1.312351e+07,1.821745,74.106471,7.0,4.0,4.0,31.0,31.0,31.0,0.225806,0.129032,0.129032,135.003085,0.161290,5.000000
4163,T1016,2018-01,393318,1225820,4.741278e+07,3.116613,38.678423,5.0,3.0,3.0,31.0,31.0,31.0,0.161290,0.096774,0.096774,120.545677,0.118280,3.666667
6677,T1017,2024-12,110716,226741,2.923558e+07,2.047952,128.938218,4.0,3.0,3.0,31.0,31.0,31.0,0.129032,0.096774,0.096774,264.059218,0.107527,3.333333
2325,T1017,2018-01,289020,647614,7.640906e+07,2.240724,117.985499,4.0,4.0,5.0,31.0,31.0,31.0,0.129032,0.129032,0.161290,264.372918,0.139785,4.333333
128073,T1018,2024-12,1572,4910,2.068734e+05,3.123410,42.133071,25.0,22.0,19.0,31.0,31.0,31.0,0.806452,0.709677,0.612903,131.598842,0.709677,22.000000
5596,T1018,2018-01,71018,573842,3.477012e+07,8.080233,60.591795,7.0,7.0,6.0,31.0,31.0,31.0,0.225806,0.225806,0.193548,489.595834,0.215054,6.666667
114,T1019,2024-12,525248,4676480,6.522749e+08,8.903375,139.479880,1.0,2.0,1.0,31.0,31.0,31.0,0.032258,0.064516,0.032258,1241.841704,0.043011,1.333333
96,T1019,2018-01,472744,9047566,7.145200e+08,19.138405,78.973726,1.0,2.0,1.0,31.0,31.0,31.0,0.032258,0.064516,0.032258,1511.431138,0.043011,1.333333
7409,T1020,2024-12,6864,75470,2.621177e+07,10.995047,347.313816,5.0,14.0,8.0,31.0,31.0,31.0,0.161290,0.451613,0.258065,3818.731595,0.290323,9.000000
1364,T1020,2018-01,69462,695037,1.086362e+08,10.006003,156.302698,3.0,9.0,4.0,31.0,31.0,31.0,0.096774,0.290323,0.129032,1563.965307,0.172043,5.333333
58854,T1021,2024-12,2899,27968,1.112168e+06,9.647465,39.765743,19.0,18.0,14.0,31.0,31.0,31.0,0.612903,0.580645,0.451613,383.638596,0.548387,17.000000
26825,T1021,2018-01,8060,124536,4.664882e+06,15.451117,37.458102,17.0,17.0,13.0,31.0,31.0,31.0,0.548387,0.548387,0.419355,578.769495,0.505376,15.666667
408340,T1022,2024-12,55,55,1.545600e+03,1.000000,28.101818,31.0,28.0,29.0,31.0,31.0,31.0,1.000000,0.903226,0.935484,28.101818,0.946237,29.333333
40530,T1022,2018-01,673,9341,2.204937e+06,13.879643,236.049398,22.0,27.0,21.0,31.0,31.0,31.0,0.709677,0.870968,0.677419,3276.281471,0.752688,23.333333
58167,T1023,2024-12,4335,4839,1.137215e+06,1.116263,235.010310,18.0,16.0,20.0,31.0,31.0,31.0,0.580645,0.516129,0.645161,262.333308,0.580645,18.000000
20167,T1023,2018-01,26338,31581,7.334424e+06,1.199066,232.241680,13.0,12.0,18.0,31.0,31.0,31.0,0.419355,0.387097,0.580645,278.473100,0.462366,14.333333
55367,T1024,2024-12,1333,4055,1.247607e+06,3.042011,307.671169,17.0,23.0,22.0,31.0,31.0,31.0,0.548387,0.741935,0.709677,935.938927,0.666667,20.666667
22322,T1024,2018-01,11944,29925,6.332208e+06,2.505442,211.602599,14.0,15.0,20.0,31.0,31.0,31.0,0.451613,0.483871,0.645161,530.158053,0.526882,16.333333
16919,T1025,2024-12,4085,32345,9.462786e+06,7.917993,292.557932,10.0,17.0,12.0,31.0,31.0,31.0,0.322581,0.548387,0.387097,2316.471554,0.419355,13.000000
26159,T1025,2018-01,3108,38337,4.886526e+06,12.334942,127.462409,16.0,22.0,17.0,31.0,31.0,31.0,0.516129,0.709677,0.548387,1572.241438,0.591398,18.333333
62554,T1026,2024-12,1278,5277,9.870957e+05,4.129108,187.056231,20.0,25.0,18.0,31.0,31.0,31.0,0.645161,0.806452,0.580645,772.375376,0.677419,21.000000
61057,T1026,2018-01,1003,6112,1.035156e+06,6.093719,169.364558,23.0,26.0,23.0,31.0,31.0,31.0,0.741935,0.838710,0.741935,1032.060000,0.774194,24.000000
42859,T1027,2024-12,13753,22068,1.986806e+06,1.604595,90.031083,14.0,10.0,16.0,31.0,31.0,31.0,0.451613,0.322581,0.516129,144.463459,0.430108,13.333333
13944,T1027,2018-01,41082,145886,1.235617e+07,3.551093,84.697443,10.0,11.0,9.0,31.0,31.0,31.0,0.322581,0.354839,0.290323,300.768492,0.322581,10.000000
75406,T1028,2024-12,6102,6108,6.724680e+05,1.000983,110.096261,21.0,15.0,17.0,31.0,31.0,31.0,0.677419,0.483871,0.548387,110.204517,0.569892,17.666667
93010,T1028,2018-01,5805,6482,4.319691e+05,1.116624,66.641325,24.0,21.0,22.0,31.0,31.0,31.0,0.774194,0.677419,0.709677,74.413276,0.720430,22.333333
291150,T1029,2024-12,15,15,1.303000e+04,1.000000,868.666667,27.0,30.0,31.0,31.0,31.0,31.0,0.870968,0.967742,1.000000,868.666667,0.946237,29.333333
367282,T1029,2018-01,24,34,3.579960e+03,1.416667,105.292941,31.0,30.0,31.0,31.0,31.0,31.0,1.000000,0.967742,1.000000,149.165000,0.989247,30.666667
82684,T1030,2024-12,1974,3842,5.526785e+05,1.946302,143.851770,22.0,21.0,23.0,31.0,31.0,31.0,0.709677,0.677419,0.741935,279.978977,0.709677,22.000000
40271,T1030,2018-01,7783,29949,2.231474e+06,3.848002,74.509133,21.0,18.0,19.0,31.0,31.0,31.0,0.677419,0.580645,0.612903,286.711296,0.623656,19.333333
257429,T1031,2024-12,129,307,2.203447e+04,2.379845,71.773518,26.0,27.0,27.0,31.0,31.0,31.0,0.838710,0.870968,0.870968,170.809845,0.860215,26.666667
207274,T1031,2018-01,503,2767,4.974348e+04,5.500994,17.977405,28.0,28.0,27.0,31.0,31.0,31.0,0.903226,0.903226,0.870968,98.893598,0.892473,27.666667
381925,T1032,2024-12,14,29,2.709370e+03,2.071429,93.426552,30.0,31.0,30.0,31.0,31.0,31.0,0.967742,1.000000,0.967742,193.526429,0.978495,30.333333
7903,T1040,2024-12,75978,135941,2.452311e+07,1.789215,180.395245,6.0,5.0,6.0,31.0,31.0,31.0,0.193548,0.161290,0.193548,322.765932,0.182796,5.666667
6020,T1040,2018-01,43820,169576,3.246717e+07,3.869831,191.460850,8.0,10.0,8.0,31.0,31.0,31.0,0.258065,0.322581,0.258065,740.921155,0.279570,8.666667
35327,T1041,2024-12,2551,2552,2.852338e+06,1.000392,1117.687332,13.0,19.0,24.0,31.0,31.0,31.0,0.419355,0.612903,0.774194,1118.125468,0.602151,18.666667
28156,T1041,2018-01,6053,6053,4.279883e+06,1.000000,707.068146,18.0,19.0,24.0,31.0,31.0,31.0,0.580645,0.612903,0.774194,707.068146,0.655914,20.333333

In [20]:
print(pctile_cols)

Index(['PAID_MONTH_PCTILE', 'BENEFICIARIES_MONTH_PCTILE',
       'CLAIMS_MONTH_PCTILE'],
      dtype='object')

In [21]:
## create average of percentile values
# combines all percentiles as a fun way to filter data

# # create a list of columns with 'MONTH_PCTILE' as part of the column name
home_health_util_sorted['MONTH_PCTILE_AVG'] = (
    home_health_util_sorted[pctile_cols].mean(axis=1)
)

# also take average rank
home_health_util_sorted['MONTH_RANK_AVG'] = (
    home_health_util_sorted[month_rank_cols].mean(axis=1)
)

filtered_health_utils_df = home_health_util_sorted[
    home_health_util_sorted['MONTH_PCTILE_AVG'] < 0.10
]

# display(filtered_health_utils_df)
filtered_health_utils_df.head()
# filtered_health_utils_df.head(1000)

,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM,PAID_PER_BENEFICIARY,PAID_MONTHLY_RANK,BENEFICIARIES_MONTHLY_RANK,CLAIMS_MONTHLY_RANK,PAID_MAX_MONTHLY_RANK,BENEFICIARIES_MAX_MONTHLY_RANK,CLAIMS_MAX_MONTHLY_RANK,PAID_MONTH_PCTILE,BENEFICIARIES_MONTH_PCTILE,CLAIMS_MONTH_PCTILE,MONTH_PCTILE_AVG,MONTH_RANK_AVG
504100,T1015,2024-12,1216414,1468053,2.924467e+08,1.206870,199.207195,240.417095,2.0,1.0,2.0,31.0,31.0,31.0,0.064516,0.032258,0.064516,0.053763,1.666667
504099,T1015,2024-11,2455604,3165696,6.151738e+08,1.289172,194.324984,250.518335,2.0,1.0,2.0,32.0,32.0,32.0,0.062500,0.031250,0.062500,0.052083,1.666667
504098,T1015,2024-10,3118842,4159943,8.044845e+08,1.333810,193.388351,257.943338,2.0,1.0,2.0,33.0,33.0,33.0,0.060606,0.030303,0.060606,0.050505,1.666667
504097,T1015,2024-09,2920799,3807733,7.147752e+08,1.303661,187.716732,244.719063,2.0,1.0,2.0,33.0,33.0,33.0,0.060606,0.030303,0.060606,0.050505,1.666667
504096,T1015,2024-08,3089005,4026213,7.586305e+08,1.303401,188.422832,245.590556,2.0,1.0,2.0,33.0,33.0,33.0,0.060606,0.030303,0.060606,0.050505,1.666667

# (above output) the percentile (average & filter) are being applied correctly
    - percentile average provides more context, is this team a dominant force or are they a one hit wonder?
        - just looking at one percentile is fine too, the intent of this is to dive depeer
## easy investigative jumping off point
    - what changed in bookends of the data'
        - were sales total  $10M the first year and $100M in the latest year? how did that change?
            - what were the highs within that data

# (below cell)
- take min/max rank of monthly claim counts
- output: first / last month's worth of data

In [223]:
remaining_cols = home_health_util_sorted.columns.difference(pctile_cols)
total_cols = remaining_cols.tolist() + pctile_cols.tolist()

max_clm_mo = filtered_health_utils_df.CLAIMS_MONTHLY_RANK.max()
min_clm_mo = filtered_health_utils_df.CLAIMS_MONTHLY_RANK.min()

print(total_cols)
print(max_clm_mo)
print(min_clm_mo)

['BENEFICIARIES_MAX_MONTHLY_RANK', 'BENEFICIARIES_MONTHLY_RANK', 'CLAIMS_MAX_MONTHLY_RANK', 'CLAIMS_MONTHLY_RANK', 'CLAIMS_PER_BENEFICIARY', 'CLAIM_FROM_MONTH', 'HCPCS_CODE', 'MONTH_PCTILE_AVG', 'MONTH_RANK_AVG', 'PAID_MAX_MONTHLY_RANK', 'PAID_MONTHLY_RANK', 'PAID_PER_BENEFICIARY', 'PAID_PER_CLAIM', 'TOTAL_CLAIMS', 'TOTAL_PAID', 'TOTAL_UNIQUE_BENEFICIARIES', 'PAID_MONTH_PCTILE', 'BENEFICIARIES_MONTH_PCTILE', 'CLAIMS_MONTH_PCTILE']
8.0
1.0

# should return the first / last elements of the dataframe, but isnt

In [224]:

# ensures pcitle columns come at the end of the DF (cleanliness, automated)
dimensional_colums_df = filtered_health_utils_df[total_cols]

# dimensional_colums_df[(dimensional_colums_df['CLAIM_FROM_MONTH'] == max_clm_mo) | (dimensional_colums_df['CLAIM_FROM_MONTH'] == min_clm_mo)]
bookend_mos_df = filtered_health_utils_df[(filtered_health_utils_df['CLAIM_FROM_MONTH'] == max_clm_mo) | (filtered_health_utils_df['CLAIM_FROM_MONTH'] == min_clm_mo)].copy()
# display(dimensional_colums_df)
# dimensional_colums_df.columns

# bookend_mos_df.columns
display(bookend_mos_df)

Empty DataFrame
Columns: [HCPCS_CODE, CLAIM_FROM_MONTH, TOTAL_UNIQUE_BENEFICIARIES, TOTAL_CLAIMS, TOTAL_PAID, CLAIMS_PER_BENEFICIARY, PAID_PER_CLAIM, PAID_MONTHLY_RANK, BENEFICIARIES_MONTHLY_RANK, CLAIMS_MONTHLY_RANK, PAID_MAX_MONTHLY_RANK, BENEFICIARIES_MAX_MONTHLY_RANK, CLAIMS_MAX_MONTHLY_RANK, PAID_MONTH_PCTILE, BENEFICIARIES_MONTH_PCTILE, CLAIMS_MONTH_PCTILE, PAID_PER_BENEFICIARY, MONTH_PCTILE_AVG, MONTH_RANK_AVG]
Index: []

# total paid by HCPCs code, sorted descending
    - the most [money spent] on any [code]
    - big numbers up top, descend to small numbers on bottom

In [32]:
hcpc_by_month.sort_values(by=['TOTAL_PAID'], ascending=False,inplace=True)
display(hcpc_by_month)
# hcpc_by_month[hcpc_by_month['HCPCS_CODE']=='T1019']

,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM
0,T1019,2024-05,820816,16668403,2.223192e+09,20.307113,133.377654
1,T1019,2024-07,775502,15774135,2.209226e+09,20.340547,140.053683
2,T1019,2024-03,815880,16268673,2.158420e+09,19.940032,132.673366
3,T1019,2024-06,773575,15206151,2.118378e+09,19.656983,139.310586
4,T1019,2024-04,815162,16059735,2.099838e+09,19.701280,130.751701
...,...,...,...,...,...,...,...
535917,M0360,2019-06,73,2926,-6.630010e+03,40.082192,-2.265895
535918,M0360,2019-08,73,3132,-6.812320e+03,42.904110,-2.175070
535919,M0360,2019-05,74,3068,-6.844470e+03,41.459459,-2.230922
535920,M0360,2019-01,73,3132,-6.973120e+03,42.904110,-2.226411
535921,M0360,2019-07,74,3232,-7.319610e+03,43.675676,-2.264731

# Paid per claim, by code, descending
    - not necessarily most dollars
        - what costs us $100k every time they bill us vs $10 every time they bill us
    - adds a potential investigative jumping off point

In [33]:
hcpc_by_month.sort_values(by=['PAID_PER_CLAIM'], ascending=False,inplace=True)
display(hcpc_by_month)

,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM
44525,J2326,2021-09,13,14,1857803.10,1.076923,132700.221429
41685,J2326,2023-12,12,16,2088864.05,1.333333,130554.003125
42579,J2326,2023-03,15,16,2010586.73,1.066667,125661.670625
28827,J2326,2020-06,26,33,4102351.20,1.269231,124313.672727
29716,J2326,2020-04,29,32,3886260.90,1.103448,121445.653125
...,...,...,...,...,...,...,...
535845,11047,2020-07,21,44,-482.25,2.095238,-10.960227
535867,M0299,2020-01,23,90,-1355.98,3.913043,-15.066444
535904,M0118,2020-03,14,137,-4598.65,9.785714,-33.566788
535850,M0145,2020-09,21,21,-845.90,1.000000,-40.280952
535886,G0235,2021-08,12,13,-1997.73,1.083333,-153.671538

# Claims per Beneficiary, by code, descending
    - are 5 people the cause of 5,000 claims?
    - are members/patients regularly being billed for this within a month?
        - doesn't paint the full picture
            - if something is billed 10k times but we only pay $1 per instance
            - is that as significant as
                - $50k/instance billed 2,000 times?
                    - probably

In [22]:
hcpc_by_month.sort_values(by=['CLAIMS_PER_BENEFICIARY'], ascending=False,inplace=True)
display(hcpc_by_month)