# Question: What if HCPC Prices Remained the Same?
## OR at minimum, saw a moderate increase in paid/claim YoY
- I will be investigating HCPC codes that saw a significant increase in paid/claim
    - some (T1019) saw as high as 200% increase across 6 years
        - verify
    - what if these increases weren't the case?
        - what if the costs stayed (relatively) level compared to 2018?
    - what would the difference in paid be?
        - which practices see significant savings amounts?
- flip-side, which codes have remained the same (or similar)?
- Data source: https://opendata.hhs.gov/datasets/medicaid-provider-spending/
## Accompaniment: https://www.youtube.com/watch?v=ocAf1rK3fxE&list=RDZgruBu-puKE&index=3

In [1]:
import pandas as pd
from dateutil.relativedelta import relativedelta

pd.set_option('display.max_rows', None) # no row limit
import pyarrow.dataset as ds
import matplotlib.pyplot as plt

# below loads the data but takes ~2.5 minutes

In [2]:
### UNCOMMENT IN CASE YOU NEED TO RUN AGAIN ####

dataset = ds.dataset(
    "/Users/luketaylor/Desktop/Pycharm/Home_Healthcare_Spending_Trends/Datasets/medicaid-provider-spending.parquet",
    format="parquet"
)
table = dataset.to_table()
medicaid_provider_spending = table.to_pandas()

# convert claim month to datetime for ease of modification later down the line
medicaid_provider_spending['CLAIM_FROM_MONTH_DATE'] = pd.to_datetime(medicaid_provider_spending['CLAIM_FROM_MONTH'])
medicaid_provider_spending['CLAIM_YEAR'] = medicaid_provider_spending['CLAIM_FROM_MONTH_DATE'].dt.year
    #medicaid_provider_spending['CLAIM_FROM_MONTH'].astype(str).str)[:4]
medicaid_provider_spending['CLAIMS_PER_BENEFICIARY'] = medicaid_provider_spending['TOTAL_CLAIMS'] / medicaid_provider_spending['TOTAL_UNIQUE_BENEFICIARIES']
medicaid_provider_spending['PAID_PER_CLAIM'] = medicaid_provider_spending['TOTAL_PAID'] / medicaid_provider_spending['TOTAL_CLAIMS']
medicaid_provider_spending.head()

,BILLING_PROVIDER_NPI_NUM,SERVICING_PROVIDER_NPI_NUM,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIM_FROM_MONTH_DATE,CLAIM_YEAR,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM
0,1376609297,1376609297,T1019,2024-07,39765,1205701,1.188877e+08,2024-07-01,2024,30.320659,98.604609
1,1376609297,1376609297,T1019,2024-08,39677,1152534,1.155611e+08,2024-08-01,2024,29.047912,100.266948
2,1376609297,1376609297,T1019,2024-05,39678,1157235,1.128233e+08,2024-05-01,2024,29.165659,97.493815
3,1376609297,1376609297,T1019,2024-06,39834,1164582,1.114492e+08,2024-06-01,2024,29.235879,95.698863
4,1376609297,1376609297,T1019,2024-09,39527,1099808,1.111998e+08,2024-09-01,2024,27.824221,101.108405

# plan of attack:
- identify codes with significant spend that saw a significant increase in paid/claim YoY
- look for top 50(?) codes to help with query-ability
- look in aggregate, which codes had the highest increase in paid/claim
- identify specific practices that saw increases in paid/claim

# 1) Identify High-Spend Codes
- right now limiting to the top 50 based on total paid

In [3]:
hcpc_code_spend = medicaid_provider_spending.groupby(['HCPCS_CODE']).agg(
    BENEFICIARY_COUNT=('TOTAL_UNIQUE_BENEFICIARIES', 'sum'),
    CLAIM_COUNT=('TOTAL_CLAIMS', 'sum'),
    PAID_AMOUNT=('TOTAL_PAID', 'sum'),
    PRACTITIONER_COUNT=('BILLING_PROVIDER_NPI_NUM', 'nunique'),
    PRACTICE_COUNT=('SERVICING_PROVIDER_NPI_NUM', 'nunique'),
)

hcpc_code_spend.reset_index(inplace=True)
hcpc_code_spend['PAID_PER_CLAIM'] = hcpc_code_spend['PAID_AMOUNT'] / hcpc_code_spend['CLAIM_COUNT']
hcpc_code_spend['PAID_PER_BENEFICIARY'] = hcpc_code_spend['PAID_AMOUNT'] / hcpc_code_spend['BENEFICIARY_COUNT']

In [4]:
top_50_codes = hcpc_code_spend.sort_values(by='PAID_AMOUNT', ascending=False).head(50)
# display(top_50_codes)
# top_50_codes.head()

top_50_codes_list = top_50_codes.HCPCS_CODE.unique().tolist()
top_50_codes_set = set(top_50_codes_list) # improved performance later down the road
print(top_50_codes_list)

['T1019', 'T1015', 'T2016', '99213', 'S5125', '99214', '99284', 'H2016', '99283', 'H2015', '99285', '90837', 'S5102', '90834', 'T2021', 'H2017', 'T1017', 'T1020', '90999', 'A0427', '92507', 'H2019', 'T2033', 'T1000', 'H2014', 'H0004', 'S5140', 'H0020', '97530', 'A0429', 'H0019', 'T1040', '99509', '00003', 'T2023', 'T1016', '97153', '97110', 'S9124', 'S5130', 'H2036', 'T2031', 'H0036', 'G0463', 'S5126', 'H0018', 'T2046', 'U0003', 'A0100', 'H2022']

# filter Medicaid utilization data to the top 50 codes by spend
- reduces query time associated due to the sheer reduction in rows
- takes 3 minutes to run

In [5]:
top_50_codes_all_util = top_50_codes_all_util = medicaid_provider_spending.loc[
    medicaid_provider_spending.HCPCS_CODE.isin(top_50_codes_set)
].copy()

top_50_codes_all_util.head()

,BILLING_PROVIDER_NPI_NUM,SERVICING_PROVIDER_NPI_NUM,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIM_FROM_MONTH_DATE,CLAIM_YEAR,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM
0,1376609297,1376609297,T1019,2024-07,39765,1205701,1.188877e+08,2024-07-01,2024,30.320659,98.604609
1,1376609297,1376609297,T1019,2024-08,39677,1152534,1.155611e+08,2024-08-01,2024,29.047912,100.266948
2,1376609297,1376609297,T1019,2024-05,39678,1157235,1.128233e+08,2024-05-01,2024,29.165659,97.493815
3,1376609297,1376609297,T1019,2024-06,39834,1164582,1.114492e+08,2024-06-01,2024,29.235879,95.698863
4,1376609297,1376609297,T1019,2024-09,39527,1099808,1.111998e+08,2024-09-01,2024,27.824221,101.108405

# Aggregate HCPC Utilization by the newly filtered DF
groupby options:
- single groupby
- df.groupby(['col_1', 'col_2']).agg({
    'col_3': 'sum',
    'col_4': 'mean'
})


- groupby multiple columns
df.groupby(['col_1', 'col_2']).agg({
    'col_3': ['sum', 'count'],
    'col_4': ['mean', 'max']
})
# takes ~30 seconds to run

In [6]:
monthly_aggregations_by_hcpc = top_50_codes_all_util.groupby(['HCPCS_CODE', 'CLAIM_FROM_MONTH']).agg(
    BENEFICIARY_COUNT=('TOTAL_UNIQUE_BENEFICIARIES', 'sum'),
    CLAIM_COUNT=('TOTAL_CLAIMS', 'sum'),
    PAID_AMOUNT=('TOTAL_PAID', 'sum'),
    PRACTITIONER_COUNT=('BILLING_PROVIDER_NPI_NUM', 'nunique'),
    PRACTICE_COUNT=('SERVICING_PROVIDER_NPI_NUM', 'nunique'),
)

monthly_aggregations_by_hcpc.reset_index(inplace=True)

monthly_aggregations_by_hcpc['CLAIM_FROM_MONTH_DATE'] = pd.to_datetime(monthly_aggregations_by_hcpc['CLAIM_FROM_MONTH'])
monthly_aggregations_by_hcpc['CLAIM_YEAR'] = monthly_aggregations_by_hcpc['CLAIM_FROM_MONTH_DATE'].dt.year

# add in metrics i'd like to break down
- claims per beneficiary
- paid per claim
- paid per beneficary

In [7]:
monthly_aggregations_by_hcpc['CLAIMS_PER_BENEFICIARY'] = monthly_aggregations_by_hcpc['CLAIM_COUNT'] / monthly_aggregations_by_hcpc['BENEFICIARY_COUNT']
monthly_aggregations_by_hcpc['PAID_PER_CLAIM'] = monthly_aggregations_by_hcpc['PAID_AMOUNT'] / monthly_aggregations_by_hcpc['CLAIM_COUNT']
monthly_aggregations_by_hcpc['PAID_PER_BENEFICIARY'] = monthly_aggregations_by_hcpc['PAID_AMOUNT'] / monthly_aggregations_by_hcpc['BENEFICIARY_COUNT']


monthly_aggregations_by_hcpc.sort_values(by=['PAID_AMOUNT','PAID_PER_CLAIM'], ascending=[False, False], inplace=True)

monthly_aggregations_by_hcpc[~monthly_aggregations_by_hcpc.HCPCS_CODE.isin(['T1019','T1015'])].head(100)

,HCPCS_CODE,CLAIM_FROM_MONTH,BENEFICIARY_COUNT,CLAIM_COUNT,PAID_AMOUNT,PRACTITIONER_COUNT,PRACTICE_COUNT,CLAIM_FROM_MONTH_DATE,CLAIM_YEAR,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM,PAID_PER_BENEFICIARY
2670,S5125,2024-07,278913,6753420,5.698249e+08,2526,1170,2024-07-01,2024,24.213357,84.375749,2043.020114
722,99213,2023-03,10236627,12300727,5.622849e+08,64085,178558,2023-03-01,2023,1.201639,45.711518,54.928729
2671,S5125,2024-08,284435,6808894,5.618175e+08,2565,1167,2024-08-01,2024,23.938313,82.512303,1975.205330
2668,S5125,2024-05,294172,6956842,5.575038e+08,2761,1374,2024-05-01,2024,23.648892,80.137484,1895.162752
2661,S5125,2023-10,299028,7026626,5.518303e+08,2790,1403,2023-10-01,2023,23.498221,78.534173,1845.413342
816,99214,2024-01,6773160,7912050,5.512468e+08,58174,168212,2024-01-01,2024,1.168148,69.671800,81.386940
3681,T2016,2024-10,54571,935843,5.501297e+08,951,850,2024-10-01,2024,17.149090,587.843987,10080.989536
2673,S5125,2024-10,276433,6614386,5.424061e+08,2623,1341,2024-10-01,2024,23.927628,82.003992,1962.161021
718,99213,2022-11,9682217,11410227,5.390282e+08,61051,168059,2022-11-01,2022,1.178473,47.240797,55.671983
806,99214,2023-03,7410685,8641775,5.383584e+08,61569,175260,2023-03-01,2023,1.166124,62.297200,72.646238
2664,S5125,2024-01,288840,6763972,5.379781e+08,2732,1377,2024-01-01,2024,23.417712,79.535821,1862.546958
2666,S5125,2024-03,294923,6687209,5.378811e+08,2750,1381,2024-03-01,2024,22.674423,80.434321,1823.801863
3680,T2016,2024-09,55305,926091,5.378172e+08,967,862,2024-09-01,2024,16.745159,580.739092,9724.568236
2667,S5125,2024-04,294393,6848111,5.358901e+08,2760,1385,2024-04-01,2024,23.261800,78.253707,1820.322069
3676,T2016,2024-05,55789,1014099,5.330474e+08,985,869,2024-05-01,2024,18.177401,525.636468,9554.704625
2663,S5125,2023-12,289503,6570686,5.306501e+08,2719,1377,2023-12-01,2023,22.696435,80.760235,1832.969428
2662,S5125,2023-11,292425,6629287,5.285894e+08,2743,1392,2023-11-01,2023,22.670042,79.735483,1807.606730
2669,S5125,2024-06,281488,6327616,5.278227e+08,2582,1257,2024-06-01,2024,22.479168,83.415729,1875.116183
724,99213,2023-05,9836076,11781851,5.262474e+08,62500,176649,2023-05-01,2023,1.197820,44.665934,53.501760
720,99213,2023-01,9283616,11248228,5.256048e+08,61737,169449,2023-01-01,2023,1.211621,46.727791,56.616393
3674,T2016,2024-03,54450,994925,5.250101e+08,969,821,2024-03-01,2024,18.272268,527.688164,9642.059623
2660,S5125,2023-09,296080,6787727,5.249631e+08,2770,1395,2023-09-01,2023,22.925314,77.340039,1773.044685
804,99214,2023-01,6838981,8037777,5.245567e+08,59177,166600,2023-01-01,2023,1.175289,65.261415,76.701003
3678,T2016,2024-07,54867,956749,5.225652e+08,964,857,2024-07-01,2024,17.437604,546.188363,9524.216195
3679,T2016,2024-08,55188,967133,5.221715e+08,970,862,2024-08-01,2024,17.524335,539.916936,9461.685253
3675,T2016,2024-04,55695,988225,5.187076e+08,975,864,2024-04-01,2024,17.743514,524.888198,9313.360970
732,99213,2024-01,8700374,10505217,5.178318e+08,58035,163247,2024-01-01,2024,1.207444,49.292826,59.518342
817,99214,2024-02,6695784,7832310,5.172616e+08,57392,166142,2024-02-01,2024,1.169738,66.042026,77.251838
3672,T2016,2024-01,54023,996606,5.162483e+08,969,814,2024-01-01,2024,18.447809,518.006438,9556.083963
2672,S5125,2024-09,280376,6379048,5.158913e+08,2693,1432,2024-09-01,2024,22.751762,80.872769,1839.997978
717,99213,2022-10,9334512,11028999,5.145102e+08,61022,166426,2022-10-01,2022,1.181529,46.650672,55.119134
3669,T2016,2023-10,53728,973233,5.125663e+08,964,802,2023-10-01,2023,18.114075,526.663505,9540.022024
3671,T2016,2023-12,54073,966827,5.118629e+08,971,817,2023-12-01,2023,17.880033,529.425502,9466.145214
3677,T2016,2024-06,55511,962117,5.100125e+08,983,868,2024-06-01,2024,17.332006,530.094050,9187.593401
710,99213,2022-03,9551868,11606391,5.098495e+08,63907,170014,2022-03-01,2022,1.215091,43.928344,53.376946
2665,S5125,2024-02,290080,6396496,5.080525e+08,2731,1369,2024-02-01,2024,22.050800,79.426687,1751.421962
808,99214,2023-05,7197289,8404157,5.071406e+08,60590,173977,2023-05-01,2023,1.167684,60.344016,70.462724
729,99213,2023-10,8993323,10591594,5.068063e+08,59482,166892,2023-10-01,2023,1.177718,47.849862,56.353621
2656,S5125,2023-05,298428,6948784,5.057512e+08,2754,1352,2023-05-01,2023,23.284625,72.782695,1694.717741
2659,S5125,2023-08,287007,6764736,5.025176e+08,2606,1200,2023-08-01,2023,23.569934,74.284884,1750.889799
2647,S5125,2022-08,281721,6634818,5.024638e+08,2536,1169,2022-08-01,2022,23.551024,75.731365,1783.551186
733,99213,2024-02,8736618,10558957,5.015904e+08,57281,162081,2024-02-01,2024,1.208586,47.503778,57.412416
708,99213,2022-01,9070297,10852822,5.015859e+08,60460,159402,2022-01-01,2022,1.196523,46.217091,55.299828
2642,S5125,2022-03,287545,6579614,4.991149e+08,2670,1334,2022-03-01,2022,22.882032,75.857772,1735.780005
3666,T2016,2023-07,54201,946055,4.985947e+08,967,809,2023-07-01,2023,17.454567,527.025074,9198.994607
3670,T2016,2023-11,54175,943749,4.935872e+08,974,814,2023-11-01,2023,17.420378,523.006898,9110.978077
721,99213,2023-02,8978770,10711191,4.931665e+08,59952,164018,2023-02-01,2023,1.192946,46.042169,54.925838
813,99214,2023-10,6690846,7714863,4.930380e+08,58190,165099,2023-10-01,2023,1.153047,63.907555,73.688444
3667,T2016,2023-08,53301,963839,4.929931e+08,946,792,2023-08-01,2023,18.082944,511.489045,9249.227772
819,99214,2024-04,6572108,7633510,4.925583e+08,57597,165235,2024-04-01,2024,1.161501,64.525789,74.946768
730,99213,2023-11,8865674,10539208,4.917308e+08,57674,162238,2023-11-01,2023,1.188766,46.657283,55.464572
2644,S5125,2022-05,291287,6661080,4.913617e+08,2668,1318,2022-05-01,2022,22.867756,73.766073,1686.864545
716,99213,2022-09,9023662,10787496,4.899242e+08,60510,163960,2022-09-01,2022,1.195468,45.415936,54.293282
3673,T2016,2024-02,54373,948471,4.882951e+08,967,817,2024-02-01,2024,17.443786,514.823473,8980.470725
719,99213,2022-12,8920417,10542772,4.876840e+08,58643,159582,2022-12-01,2022,1.181870,46.257665,54.670540
2658,S5125,2023-07,283108,6502963,4.875367e+08,2512,1143,2023-07-01,2023,22.969902,74.971468,1722.087278
2674,S5125,2024-11,262199,5907693,4.873867e+08,2426,1190,2024-11-01,2024,22.531333,82.500350,1858.842875
704,99213,2021-09,9243680,11097622,4.869259e+08,61899,160427,2021-09-01,2021,1.200563,43.876599,52.676629
811,99214,2023-08,6767068,7870514,4.864627e+08,58622,165189,2023-08-01,2023,1.163061,61.808249,71.886775
3668,T2016,2023-09,53508,922134,4.860490e+08,948,789,2023-09-01,2023,17.233573,527.091532,9083.670156
2657,S5125,2023-06,290497,6519468,4.859323e+08,2633,1279,2023-06-01,2023,22.442462,74.535573,1672.761803
2646,S5125,2022-07,273406,6341758,4.843355e+08,2438,1129,2022-07-01,2022,23.195387,76.372434,1771.488164
818,99214,2024-03,6385367,7407566,4.827579e+08,55981,160548,2024-03-01,2024,1.160085,65.170916,75.603777
715,99213,2022-08,8932724,10695153,4.819564e+08,61527,166090,2022-08-01,2022,1.197300,45.063067,53.954023
2652,S5125,2023-01,291758,6738805,4.799081e+08,2761,1375,2023-01-01,2023,23.097242,71.215613,1644.884216
727,99213,2023-08,8975655,10703813,4.795627e+08,60063,167220,2023-08-01,2023,1.192538,44.802976,53.429268
712,99213,2022-05,8775772,10405102,4.794205e+08,60999,162264,2022-05-01,2022,1.185662,46.075517,54.630003
794,99214,2022-03,6690154,7894520,4.778180e+08,59499,160445,2022-03-01,2022,1.180021,60.525279,71.421080
2651,S5125,2022-12,294446,6712877,4.777828e+08,2755,1355,2022-12-01,2022,22.798330,71.174072,1622.649973
735,99213,2024-04,8503513,10187538,4.769193e+08,56760,160267,2024-04-01,2024,1.198039,46.813986,56.084969
2645,S5125,2022-06,279694,6234254,4.765855e+08,2552,1265,2022-06-01,2022,22.289552,76.446270,1703.953124
707,99213,2021-12,8778960,10434331,4.757527e+08,59792,155815,2021-12-01,2021,1.188561,45.594942,54.192378
706,99213,2021-11,8932736,10640125,4.750639e+08,60625,158716,2021-11-01,2021,1.191138,44.648337,53.182349
2643,S5125,2022-04,291346,6524177,4.749633e+08,2673,1327,2022-04-01,2022,22.393227,72.800494,1630.237963
802,99214,2022-11,6549257,7554019,4.742787e+08,56479,155877,2022-11-01,2022,1.153416,62.784943,72.417170
814,99214,2023-11,6448868,7443672,4.735896e+08,56188,158657,2023-11-01,2023,1.154260,63.623121,73.437640
2649,S5125,2022-10,293922,6733853,4.729792e+08,2754,1384,2022-10-01,2022,22.910340,70.239021,1609.199874
734,99213,2024-03,8386879,10050356,4.727858e+08,56080,157916,2024-03-01,2024,1.198343,47.041694,56.372075
805,99214,2023-02,6436251,7449064,4.724817e+08,57103,158947,2023-02-01,2023,1.157361,63.428330,73.409457
2655,S5125,2023-04,295328,6529277,4.724232e+08,2747,1356,2023-04-01,2023,22.108561,72.354590,1599.655839
705,99213,2021-10,8844359,10423480,4.718865e+08,61569,159274,2021-10-01,2021,1.178546,45.271496,53.354520
820,99214,2024-05,6333554,7319189,4.715162e+08,56673,161698,2024-05-01,2024,1.155621,64.421922,74.447336
723,99213,2023-04,8866017,10519486,4.712789e+08,59550,164710,2023-04-01,2023,1.186495,44.800563,53.155650
2650,S5125,2022-11,295116,6644289,4.680832e+08,2764,1371,2022-11-01,2022,22.514161,70.448947,1586.098909
728,99213,2023-09,8572427,10125407,4.646263e+08,57519,159304,2023-09-01,2023,1.181160,45.887174,54.200089
3652,T2016,2022-05,55722,910414,4.635701e+08,961,805,2022-05-01,2022,16.338502,509.185996,8319.336332
703,99213,2021-08,8894176,10699292,4.619636e+08,61286,157739,2021-08-01,2021,1.202955,43.177027,51.940014
711,99213,2022-04,8630969,10306629,4.615820e+08,60592,159519,2022-04-01,2022,1.194145,44.784967,53.479747
736,99213,2024-05,8225853,9819071,4.601103e+08,55873,157335,2024-05-01,2024,1.193684,46.858840,55.934658
801,99214,2022-10,6419145,7437156,4.586420e+08,56845,155598,2022-10-01,2022,1.158590,61.669001,71.449076
2639,S5125,2021-12,290888,6679893,4.586312e+08,2669,1358,2021-12-01,2021,22.963797,68.658462,1576.658984
2654,S5125,2023-03,294349,6207974,4.581272e+08,2762,1368,2023-03-01,2023,21.090522,73.796579,1556.408367
731,99213,2023-12,8219187,9692230,4.542432e+08,54697,151619,2023-12-01,2023,1.179220,46.866742,55.266201
684,99213,2020-01,8784425,10744730,4.539309e+08,61040,151479,2020-01-01,2020,1.223157,42.246841,51.674515
2648,S5125,2022-09,292692,6647780,4.507305e+08,2734,1358,2022-09-01,2022,22.712544,67.801659,1539.948174
825,99214,2024-10,6032525,6861868,4.498610e+08,54083,155914,2024-10-01,2024,1.137479,65.559557,74.572592
799,99214,2022-08,6353417,7438325,4.485998e+08,57237,156225,2022-08-01,2022,1.170760,60.309256,70.607650
807,99214,2023-04,6411058,7385056,4.483328e+08,57184,159646,2023-04-01,2023,1.151925,60.708106,69.931166
812,99214,2023-09,6186267,7114305,4.470696e+08,55576,154891,2023-09-01,2023,1.150016,62.840937,72.268073
3653,T2016,2022-06,55513,873293,4.466489e+08,956,791,2022-06-01,2022,15.731324,511.453604,8045.842447

# re-aggregate at the monthly level, look for a HCPC's first & last month with claims billed
- im omitting 2024-11 and 2024-12 due to insufficient claims data
    - looks like the data has runout issues

## also grabbing paid/claim by month and HCPC to enable me to easily grab first + last month's amounts

In [8]:
claims_util_w_runout = monthly_aggregations_by_hcpc[monthly_aggregations_by_hcpc['CLAIM_FROM_MONTH'] <= '2024-09']

start_and_end_months_by_hcpc = claims_util_w_runout.groupby(['HCPCS_CODE','CLAIM_YEAR']).agg(
    FIRST_MONTH=('CLAIM_FROM_MONTH', 'min'),
    LAST_MONTH=('CLAIM_FROM_MONTH', 'max'),
    TOTAL_MONTHS=('CLAIM_FROM_MONTH', 'nunique'),
    YEARLY_CLAIMS=('CLAIM_COUNT','sum'),
)
start_and_end_months_by_hcpc.reset_index(inplace=True)

hcpc_paid_per_claim = monthly_aggregations_by_hcpc[['HCPCS_CODE','CLAIM_FROM_MONTH', 'CLAIM_YEAR','PAID_PER_CLAIM','CLAIM_COUNT']]

start_and_end_months_by_hcpc.head()
# hcpc_paid_per_claim.head()

  HCPCS_CODE  CLAIM_YEAR FIRST_MONTH LAST_MONTH  TOTAL_MONTHS  YEARLY_CLAIMS
0      00003        2018     2018-01    2018-12            12        4744653
1      00003        2019     2019-01    2019-12            12        3807981
2      00003        2020     2020-01    2020-12            12        2516866
3      00003        2021     2021-01    2021-12            12        2556097
4      00003        2022     2022-01    2022-12            12        2091562

# get first and last month's paid/claim amount
- get the difference and calculate the annualized + monthly change
- which codes stand out?
- rough & dirty savings calc
- add 5% increase to cost/claim in a given year
    - that * claim count gives us an idea
    - better implementation:
        - monthly-ize the 5% growth rate, apply to the monthly util database
        - if > 1.05% annual, tough time buddy

In [9]:
first_paid_per_claim = pd.merge(
    left=start_and_end_months_by_hcpc,
    right=hcpc_paid_per_claim,
    how='left',
    left_on=['FIRST_MONTH', 'CLAIM_YEAR', 'HCPCS_CODE'],
    right_on=['CLAIM_FROM_MONTH', 'CLAIM_YEAR', 'HCPCS_CODE'],
)


first_paid_per_claim.drop(columns=['CLAIM_FROM_MONTH'], inplace=True)
first_paid_per_claim.rename(columns={
    'PAID_PER_CLAIM':'BEGINNING_PAID_PER_CLAIM',
    # 'CLAIM_COUNT':'BEGINNING_CLAIM_COUNT',
    }, inplace=True)


paid_per_claim_diffs = pd.merge(
    left=first_paid_per_claim,
    right=hcpc_paid_per_claim,
    how='left',
    left_on=['LAST_MONTH', 'CLAIM_YEAR', 'HCPCS_CODE'],
    right_on=['CLAIM_FROM_MONTH', 'CLAIM_YEAR', 'HCPCS_CODE'],
)

paid_per_claim_diffs.drop(columns=['CLAIM_FROM_MONTH'], inplace=True)
paid_per_claim_diffs.rename(columns={
    'PAID_PER_CLAIM':'ENDING_PAID_PER_CLAIM',
    # 'CLAIM_COUNT':'ENDING_CLAIM_COUNT',
    }, inplace=True)


paid_per_claim_diffs['PAID_PER_CLAIM_PCT_CHANGE'] = (paid_per_claim_diffs['ENDING_PAID_PER_CLAIM'] / paid_per_claim_diffs['BEGINNING_PAID_PER_CLAIM'])

paid_per_claim_diffs["MONTHLY_GROWTH_RATE"] = (
    paid_per_claim_diffs["PAID_PER_CLAIM_PCT_CHANGE"]
    ** (1 / paid_per_claim_diffs["TOTAL_MONTHS"])
)

paid_per_claim_diffs["ANNUAL_GROWTH_RATE"] = ( paid_per_claim_diffs["MONTHLY_GROWTH_RATE"] ** 12)
paid_per_claim_diffs['5_PCT_END_OF_YEAR_PPC'] = paid_per_claim_diffs['BEGINNING_PAID_PER_CLAIM'] * 1.05
paid_per_claim_diffs['EST_5_PCT_SAVINGS'] = paid_per_claim_diffs['5_PCT_END_OF_YEAR_PPC'] * paid_per_claim_diffs['YEARLY_CLAIMS']



col_order = [
    'HCPCS_CODE'
    ,'FIRST_MONTH','BEGINNING_PAID_PER_CLAIM'
    # ,'BEGINNING_CLAIM_COUNT'
    ,'LAST_MONTH','ENDING_PAID_PER_CLAIM'
    # ,'ENDING_CLAIM_COUNT'
    ,'PAID_PER_CLAIM_PCT_CHANGE','TOTAL_MONTHS','MONTHLY_GROWTH_RATE','ANNUAL_GROWTH_RATE'
    ,'5_PCT_END_OF_YEAR_PPC', 'EST_5_PCT_SAVINGS'
]

paid_per_claim_diffs[paid_per_claim_diffs['ANNUAL_GROWTH_RATE']>=1.05][col_order]

,HCPCS_CODE,FIRST_MONTH,BEGINNING_PAID_PER_CLAIM,LAST_MONTH,ENDING_PAID_PER_CLAIM,PAID_PER_CLAIM_PCT_CHANGE,TOTAL_MONTHS,MONTHLY_GROWTH_RATE,ANNUAL_GROWTH_RATE,5_PCT_END_OF_YEAR_PPC,EST_5_PCT_SAVINGS
5,00003,2023-01,293.298126,2023-12,310.630711,1.059095,12,1.004796,1.059095,307.963032,7.108652e+08
7,90834,2018-01,61.798758,2018-12,66.023013,1.068355,12,1.005525,1.068355,64.888696,8.038946e+08
8,90834,2019-01,68.621924,2019-12,75.875744,1.105707,12,1.008409,1.105707,72.053021,9.827574e+08
10,90834,2021-01,76.939542,2021-12,81.096267,1.054026,12,1.004394,1.054026,80.786519,1.421943e+09
11,90834,2022-01,82.918498,2022-12,87.586051,1.056291,12,1.004574,1.056291,87.064423,1.550834e+09
12,90834,2023-01,86.741205,2023-12,95.486677,1.100823,12,1.008037,1.100823,91.078265,1.629273e+09
14,90837,2018-01,71.747635,2018-12,77.180511,1.075722,12,1.006101,1.075722,75.335017,9.642649e+08
15,90837,2019-01,78.676394,2019-12,82.753488,1.051821,12,1.004219,1.051821,82.610214,1.168327e+09
19,90837,2023-01,95.034011,2023-12,119.506543,1.257513,12,1.019278,1.257513,99.785711,2.453046e+09
25,90999,2022-01,77.619265,2022-12,85.315747,1.099157,12,1.007910,1.099157,81.500229,1.149948e+09
26,90999,2023-01,88.856167,2023-12,102.696507,1.155761,12,1.012136,1.155761,93.298976,1.216257e+09
27,90999,2024-01,92.389528,2024-09,124.499676,1.347552,9,1.033699,1.488426,97.009005,7.965109e+08
29,92507,2019-01,48.768475,2019-12,52.407539,1.074619,12,1.006015,1.074619,51.206899,7.786083e+08
30,92507,2020-01,51.760479,2020-12,58.397009,1.128216,12,1.010104,1.128216,54.348503,7.670900e+08
31,92507,2021-01,55.966543,2021-12,59.175335,1.057334,12,1.004657,1.057334,58.764871,1.211869e+09
35,97110,2018-01,34.792352,2018-12,37.391404,1.074702,12,1.006022,1.074702,36.531969,5.554520e+08
42,97153,2019-01,107.371955,2019-12,158.045625,1.471945,12,1.032740,1.471945,112.740553,2.455272e+08
43,97153,2020-01,153.522783,2020-12,169.827090,1.106201,12,1.008446,1.106201,161.198922,3.910795e+08
44,97153,2021-01,166.208933,2021-12,178.625407,1.074704,12,1.006022,1.074704,174.519380,6.780163e+08
45,97153,2022-01,179.026369,2022-12,212.783260,1.188558,12,1.014499,1.188558,187.977688,8.819526e+08
46,97153,2023-01,202.797998,2023-12,221.083255,1.090165,12,1.007220,1.090165,212.937898,1.372314e+09
47,97153,2024-01,212.945372,2024-09,228.747262,1.074206,9,1.007985,1.100146,223.592641,1.189222e+09
48,97530,2018-01,40.615879,2018-12,45.175761,1.112268,12,1.008906,1.112268,42.646673,4.705798e+08
49,97530,2019-01,46.614165,2019-12,49.474139,1.061354,12,1.004974,1.061354,48.944873,7.274754e+08
53,97530,2023-01,48.262333,2023-12,50.884255,1.054326,12,1.004418,1.054326,50.675450,1.207257e+09
58,99213,2021-01,43.325266,2021-12,45.594942,1.052387,12,1.004264,1.052387,45.491529,5.379162e+09
70,99283,2019-01,83.678641,2019-12,89.771956,1.072818,12,1.005875,1.072818,87.862573,2.196194e+09
71,99283,2020-01,94.294889,2020-12,99.248133,1.052529,12,1.004275,1.052529,99.009633,1.744888e+09
72,99283,2021-01,98.376945,2021-12,108.006218,1.097881,12,1.007812,1.097881,103.295792,2.453384e+09
73,99283,2022-01,108.771338,2022-12,116.207634,1.068366,12,1.005526,1.068366,114.209904,3.261833e+09
74,99283,2023-01,130.895411,2023-12,142.335237,1.087397,12,1.007007,1.087397,137.440181,3.142949e+09
78,99284,2020-01,109.341494,2020-12,117.324917,1.073014,12,1.005890,1.073014,114.808569,2.033191e+09
79,99284,2021-01,118.274051,2021-12,127.374428,1.076943,12,1.006196,1.076943,124.187753,2.894173e+09
83,99285,2018-01,109.547951,2018-12,117.847353,1.075760,12,1.006104,1.075760,115.025349,1.616876e+09
90,99509,2018-01,49.233008,2018-12,54.099249,1.098841,12,1.007886,1.098841,51.694659,5.818749e+08
91,99509,2019-01,51.814708,2019-12,55.269534,1.066677,12,1.005393,1.066677,54.405443,6.167637e+08
92,99509,2020-01,54.387988,2020-12,72.625039,1.335314,12,1.024390,1.335314,57.107387,6.444559e+08
94,99509,2022-01,73.867159,2022-12,80.763282,1.093358,12,1.007466,1.093358,77.560517,9.056892e+08
95,99509,2023-01,79.111282,2023-12,84.627964,1.069733,12,1.005633,1.069733,83.066846,9.685917e+08
96,99509,2024-01,81.610199,2024-09,85.104317,1.042815,9,1.004669,1.057490,85.690709,7.221544e+08
97,A0100,2018-01,19.079766,2018-12,20.686999,1.084238,12,1.006763,1.084238,20.033754,3.612797e+08
99,A0100,2020-01,22.805994,2020-12,24.500114,1.074284,12,1.005989,1.074284,23.946293,4.248133e+08
101,A0100,2022-01,25.318790,2022-12,28.969111,1.144174,12,1.011287,1.144174,26.584730,6.349338e+08
104,A0427,2018-01,130.442047,2018-12,157.702559,1.208986,12,1.015941,1.208986,136.964150,6.046126e+08
105,A0427,2019-01,157.485131,2019-12,172.505767,1.095378,12,1.007621,1.095378,165.359388,7.801166e+08
106,A0427,2020-01,194.318724,2020-12,214.647237,1.104614,12,1.008326,1.104614,204.034661,9.354542e+08
108,A0427,2022-01,231.495918,2022-12,247.280205,1.068184,12,1.005512,1.068184,243.070714,1.275124e+09
109,A0427,2023-01,265.971441,2023-12,303.653342,1.141676,12,1.011103,1.141676,279.270013,1.482435e+09
110,A0427,2024-01,300.410399,2024-09,321.405113,1.069887,9,1.007534,1.094251,315.430919,1.106440e+09
111,A0429,2018-01,106.924264,2018-12,132.446787,1.238697,12,1.017998,1.238697,112.270477,4.154027e+08
112,A0429,2019-01,135.160573,2019-12,146.164732,1.081415,12,1.006544,1.081415,141.918602,5.995957e+08
113,A0429,2020-01,151.876490,2020-12,168.370272,1.108600,12,1.008629,1.108600,159.470315,6.534119e+08
114,A0429,2021-01,179.583963,2021-12,195.379340,1.087955,12,1.007050,1.087955,188.563161,8.515993e+08
115,A0429,2022-01,196.984829,2022-12,219.381986,1.113700,12,1.009014,1.113700,206.834071,1.039207e+09
116,A0429,2023-01,237.964871,2023-12,252.552232,1.061300,12,1.004970,1.061300,249.863114,1.305351e+09
117,A0429,2024-01,258.351021,2024-09,281.296265,1.088814,9,1.009499,1.120138,271.268572,9.744228e+08
125,H0004,2018-01,59.844438,2018-12,66.319645,1.108201,12,1.008598,1.108201,62.836660,5.958904e+08
126,H0004,2019-01,68.588648,2019-12,74.986616,1.093280,12,1.007460,1.093280,72.018080,6.879840e+08
127,H0004,2020-01,78.589409,2020-12,86.466837,1.100235,12,1.007992,1.100235,82.518879,8.954953e+08
128,H0004,2021-01,87.355583,2021-12,94.062742,1.076780,12,1.006184,1.076780,91.723362,1.002811e+09
129,H0004,2022-01,95.248882,2022-12,113.123612,1.187663,12,1.014436,1.187663,100.011327,1.153360e+09
133,H0018,2019-01,316.975541,2019-12,369.012803,1.164168,12,1.012748,1.164168,332.824318,5.326407e+08
134,H0018,2020-01,359.240864,2020-12,386.914113,1.077033,12,1.006203,1.077033,377.202907,5.386676e+08
135,H0018,2021-01,379.858901,2021-12,417.447274,1.098954,12,1.007894,1.098954,398.851846,7.224651e+08
136,H0018,2022-01,461.935220,2022-12,505.240004,1.093746,12,1.007495,1.093746,485.031981,7.897072e+08
137,H0018,2023-01,488.287067,2023-12,526.620769,1.078506,12,1.006318,1.078506,512.701420,7.647485e+08
140,H0019,2019-01,206.519561,2019-12,247.778205,1.199781,12,1.015294,1.199781,216.845539,6.532160e+08
141,H0019,2020-01,249.549474,2020-12,286.642440,1.148640,12,1.011615,1.148640,262.026948,7.717076e+08
142,H0019,2021-01,288.922415,2021-12,306.923542,1.062304,12,1.005049,1.062304,303.368536,8.957666e+08
143,H0019,2022-01,308.104657,2022-12,323.981927,1.051532,12,1.004196,1.051532,323.509890,1.006463e+09
144,H0019,2023-01,332.803360,2023-12,360.528590,1.083308,12,1.006691,1.083308,349.443528,1.171214e+09
145,H0019,2024-01,361.533195,2024-09,421.193748,1.165021,9,1.017116,1.225872,379.609855,8.564909e+08
147,H0020,2019-01,16.563371,2019-12,19.278175,1.163904,12,1.012729,1.163904,17.391539,7.793605e+08
151,H0020,2023-01,22.019902,2023-12,26.942658,1.223559,12,1.016956,1.223559,23.120897,9.952100e+08
152,H0020,2024-01,27.605597,2024-09,29.752559,1.077773,9,1.008357,1.105019,28.985877,7.180523e+08
154,H0036,2019-01,70.601198,2019-12,83.994176,1.189699,12,1.014580,1.189699,74.131258,5.748188e+08
156,H0036,2021-01,75.912765,2021-12,84.899611,1.118384,12,1.009367,1.118384,79.708404,5.663718e+08
158,H0036,2023-01,82.144277,2023-12,86.268611,1.050208,12,1.004091,1.050208,86.251490,7.710544e+08
160,H2014,2018-01,81.952218,2018-12,98.659620,1.203868,12,1.015582,1.203868,86.049828,7.831824e+08
162,H2014,2020-01,97.745555,2020-12,122.417622,1.252411,12,1.018933,1.252411,102.632833,7.386035e+08
163,H2014,2021-01,120.805071,2021-12,129.980205,1.075950,12,1.006119,1.075950,126.845325,9.495496e+08
164,H2014,2022-01,130.190140,2022-12,170.711784,1.311250,12,1.022839,1.311250,136.699648,1.058670e+09
170,H2015,2021-01,141.919851,2021-12,155.289191,1.094203,12,1.007530,1.094203,149.015843,2.691416e+09
171,H2015,2022-01,151.905110,2022-12,176.603850,1.162593,12,1.012634,1.162593,159.500366,2.844401e+09
174,H2016,2018-01,202.679909,2018-12,319.043255,1.574124,12,1.038532,1.574124,212.813904,1.026649e+09
176,H2016,2020-01,302.662076,2020-12,318.876225,1.053572,12,1.004358,1.053572,317.795180,2.310690e+09
180,H2016,2024-01,333.923432,2024-09,348.886450,1.044810,9,1.004882,1.060188,350.619604,3.417123e+09
182,H2017,2019-01,88.292088,2019-12,101.174437,1.145906,12,1.011414,1.145906,92.706692,1.104610e+09
183,H2017,2020-01,101.973418,2020-12,107.593215,1.055110,12,1.004480,1.055110,107.072088,1.263900e+09
185,H2017,2022-01,108.903811,2022-12,122.951707,1.128994,12,1.010162,1.128994,114.349001,1.118629e+09
189,H2019,2019-01,102.646296,2019-12,108.913669,1.061058,12,1.004951,1.061058,107.778611,1.114633e+09
193,H2019,2023-01,98.362216,2023-12,105.973893,1.077384,12,1.006231,1.077384,103.280327,1.085088e+09
194,H2019,2024-01,108.626652,2024-09,119.417356,1.099338,9,1.010579,1.134596,114.057984,9.202334e+08
198,H2022,2021-01,402.117278,2021-12,485.780858,1.208058,12,1.015876,1.208058,422.223142,4.719277e+08
199,H2022,2022-01,479.124610,2022-12,604.584639,1.261853,12,1.019571,1.261853,503.080840,4.938911e+08
200,H2022,2023-01,519.103325,2023-12,634.151847,1.221629,12,1.016822,1.221629,545.058491,6.604234e+08
201,H2022,2024-01,632.101498,2024-09,670.467765,1.060696,9,1.006569,1.081736,663.706573,4.881150e+08
202,H2036,2018-01,200.508345,2018-12,268.122738,1.337215,12,1.024511,1.337215,210.533762,2.057176e+08
205,H2036,2021-01,224.572347,2021-12,245.223046,1.091956,12,1.007358,1.091956,235.800964,4.905393e+08
206,H2036,2022-01,240.280574,2022-12,284.918511,1.185774,12,1.014301,1.185774,252.294602,7.953206e+08
212,S5102,2021-01,79.358999,2021-12,84.542984,1.065323,12,1.005287,1.065323,83.326949,1.348822e+09
213,S5102,2022-01,82.054081,2022-12,86.462857,1.053730,12,1.004371,1.053730,86.156785,1.525221e+09
214,S5102,2023-01,86.970626,2023-12,97.591799,1.122124,12,1.009648,1.122124,91.319157,1.514081e+09
215,S5102,2024-01,94.166147,2024-09,103.424791,1.098322,9,1.010475,1.133200,98.874454,1.340375e+09
221,S5125,2023-01,71.215613,2023-12,80.760235,1.134024,12,1.010536,1.134024,74.776394,5.917978e+09
225,S5126,2020-01,69.931652,2020-12,78.817698,1.127068,12,1.010018,1.127068,73.428235,5.022407e+08
226,S5126,2021-01,81.538940,2021-12,99.095374,1.215313,12,1.016383,1.215313,85.615887,6.729553e+08
227,S5126,2022-01,97.015651,2022-12,108.592496,1.119330,12,1.009438,1.119330,101.866433,7.300305e+08
231,S5130,2019-01,49.279459,2019-12,54.590464,1.107773,12,1.008566,1.107773,51.743432,6.596179e+08
236,S5130,2024-01,51.522177,2024-09,68.304508,1.325730,9,1.031825,1.456376,54.098286,6.507061e+08
240,S5140,2021-01,145.096232,2021-12,163.995814,1.130255,12,1.010256,1.130255,152.351044,8.524946e+08
242,S5140,2023-01,147.371744,2023-12,159.317642,1.081060,12,1.006516,1.081060,154.740331,1.243076e+09
244,S9124,2018-01,263.297508,2018-12,304.780068,1.157550,12,1.012267,1.157550,276.462384,3.213809e+08
245,S9124,2019-01,332.348850,2019-12,379.423669,1.141643,12,1.011100,1.141643,348.966292,5.628816e+08
246,S9124,2020-01,368.598132,2020-12,402.896997,1.093052,12,1.007442,1.093052,387.028039,6.742199e+08
248,S9124,2022-01,424.139316,2022-12,488.343289,1.151375,12,1.011816,1.151375,445.346282,9.061007e+08
252,T1000,2019-01,307.653671,2019-12,332.935208,1.082175,12,1.006603,1.082175,323.036355,4.736869e+08
253,T1000,2020-01,331.789340,2020-12,412.105857,1.242071,12,1.018229,1.242071,348.378807,6.299647e+08
256,T1000,2023-01,423.080124,2023-12,480.337960,1.135336,12,1.010634,1.135336,444.234131,1.390043e+09
263,T1015,2023-01,155.065947,2023-12,170.199436,1.097594,12,1.007790,1.097594,162.819244,8.691753e+09
264,T1015,2024-01,175.384873,2024-09,187.717078,1.070315,9,1.007579,1.094836,184.154116,6.905148e+09
265,T1016,2018-01,38.678423,2018-12,43.825079,1.133063,12,1.010465,1.133063,40.612344,5.795726e+08
266,T1016,2019-01,42.327600,2019-12,52.805351,1.247539,12,1.018602,1.247539,44.443980,6.450532e+08
268,T1016,2021-01,49.091881,2021-12,51.849356,1.056170,12,1.004564,1.056170,51.546475,7.364566e+08
269,T1016,2022-01,51.175454,2022-12,87.133289,1.702638,12,1.045346,1.702638,53.734227,7.352117e+08
271,T1016,2024-01,55.705136,2024-09,58.118614,1.043326,9,1.004724,1.058181,58.490393,5.954502e+08
275,T1017,2021-01,93.122341,2021-12,105.896824,1.137180,12,1.010770,1.137180,97.778458,1.118510e+09
276,T1017,2022-01,105.352043,2022-12,116.823279,1.108885,12,1.008650,1.108885,110.619645,1.267813e+09
277,T1017,2023-01,117.078163,2023-12,129.658601,1.107453,12,1.008542,1.107453,122.932071,1.565602e+09
278,T1017,2024-01,124.373894,2024-09,142.997342,1.149738,9,1.015625,1.204476,130.592589,1.332578e+09
279,T1019,2018-01,78.973726,2018-12,88.693717,1.123079,12,1.009720,1.123079,82.922413,9.413063e+09
280,T1019,2019-01,91.688712,2019-12,101.945743,1.111868,12,1.008876,1.111868,96.273148,1.381029e+10
283,T1019,2022-01,109.089928,2022-12,122.829088,1.125943,12,1.009934,1.125943,114.544424,1.972292e+10
284,T1019,2023-01,118.602321,2023-12,128.120419,1.080252,12,1.006454,1.080252,124.532438,2.295904e+10
286,T1020,2018-01,156.302698,2018-12,208.654874,1.334941,12,1.024366,1.334941,164.117833,8.034464e+08
287,T1020,2019-01,218.219008,2019-12,252.223149,1.155826,12,1.012141,1.155826,229.129958,1.028643e+09
288,T1020,2020-01,255.968314,2020-12,275.663839,1.076945,12,1.006196,1.076945,268.766730,1.439292e+09
297,T1040,2022-01,171.177612,2022-12,192.350036,1.123687,12,1.009765,1.123687,179.736493,9.287003e+08
301,T2016,2019-01,467.775245,2019-12,520.452310,1.112612,12,1.008932,1.112612,491.164008,4.926067e+09
305,T2016,2023-01,410.913293,2023-12,529.425502,1.288412,12,1.021342,1.288412,431.458958,4.695944e+09
306,T2016,2024-01,518.006438,2024-09,580.739092,1.121104,9,1.012783,1.164648,543.906760,4.761586e+09
309,T2021,2020-01,134.321124,2020-12,141.299532,1.051953,12,1.004230,1.051953,141.037181,8.128244e+08
310,T2021,2021-01,142.365470,2021-12,153.300843,1.076812,12,1.006186,1.076812,149.483743,9.924217e+08
311,T2021,2022-01,149.585884,2022-12,172.683675,1.154412,12,1.012038,1.154412,157.065178,1.286495e+09
313,T2021,2024-01,172.213374,2024-09,188.719444,1.095847,9,1.010222,1.129795,180.824043,1.350942e+09
314,T2023,2018-01,337.958631,2018-12,400.325168,1.184539,12,1.014213,1.184539,354.856562,5.318345e+08
315,T2023,2019-01,390.805812,2019-12,421.690890,1.079029,12,1.006359,1.079029,410.346103,6.039737e+08
317,T2023,2021-01,413.202842,2021-12,448.443151,1.085286,12,1.006844,1.085286,433.862984,8.116904e+08
319,T2023,2023-01,375.201021,2023-12,418.111613,1.114367,12,1.009065,1.114367,393.961072,8.057359e+08
322,T2031,2019-01,229.991106,2019-12,304.689703,1.324789,12,1.023715,1.324789,241.490661,4.394183e+08
323,T2031,2020-01,313.324292,2020-12,338.084787,1.079025,12,1.006358,1.079025,328.990506,4.654475e+08
326,T2031,2023-01,323.432407,2023-12,362.193422,1.119843,12,1.009477,1.119843,339.604027,9.828691e+08
327,T2031,2024-01,398.889920,2024-09,437.057894,1.095685,9,1.010205,1.129574,418.834416,9.319652e+08
328,T2033,2018-01,357.691278,2018-12,397.302309,1.110741,12,1.008791,1.110741,375.575842,8.451395e+08
330,T2033,2020-01,358.708180,2020-12,390.640387,1.089020,12,1.007132,1.089020,376.643589,8.870936e+08
331,T2033,2021-01,391.340699,2021-12,465.677370,1.189954,12,1.014598,1.189954,410.907734,9.668034e+08
332,T2033,2022-01,471.230858,2022-12,532.498504,1.130016,12,1.010238,1.130016,494.792401,1.167375e+09
334,T2033,2024-01,522.050990,2024-09,582.176915,1.115173,9,1.012186,1.156439,548.153540,1.076358e+09
337,T2046,2020-01,270.179355,2020-12,316.051208,1.169783,12,1.013154,1.169783,283.688322,5.812740e+08
338,T2046,2021-01,315.631278,2021-12,346.603536,1.098128,12,1.007831,1.098128,331.412842,6.152278e+08
340,T2046,2023-01,234.097934,2023-12,376.743286,1.609340,12,1.040449,1.609340,245.802831,5.802702e+08
343,U0003,2020-03,34.579521,2020-12,66.845231,1.933087,10,1.068133,2.205473,36.308497,4.976503e+08
347,U0003,2024-01,52.434938,2024-09,63.219895,1.205683,9,1.021000,1.283248,55.056685,1.531677e+05

# 23/50 codes have an annual growth rate of > 5%
## what if we cap this amount at 5%?
- savings logic would be:
- paid/claim not to exceed 5% annually
- easier to just step increase the payment amounts by nmonth
    - if no significant increase, keep as-is

In [10]:
pow(1.05, 1/12)

1.0040741237836484

# mock logic as of a single case to reduce rows + noise
- i want to look at the first month's paid for a given claim code
- and iteratively apply the 5% annualized growth

# starting point:
- monthly_paid_per_claim_increase * last month's paid per claim
- eventually we'll want to start from a baseline - e.g. if we're working with month 4, pulling month 3's PPC to adjust for month 4 but month 3 is 1% higher than month 2, we're off kilter
- starting from the beginning of year (or from the start of data?) progress each month's payment amount by 1.05 ^ (1/12) (5% annualized)

# rank by HCPC and provider to find the first month for sake of getting the first month's paid per claim
## make sure to filter to > $0 paid
# also want sizable claim volume (add later)
# not U0003 when it first began to be billed
code:
- home_health_util_sorted['CLAIMS_MONTHLY_RANK'] = home_health_util_sorted.groupby('CLAIM_FROM_MONTH')['TOTAL_CLAIMS'].rank(method='min', ascending=False)

In [11]:
## don't want zero claims throwing off pricing comparisons
non_zero_paid = top_50_codes_all_util[top_50_codes_all_util['TOTAL_PAID'] > 0]

non_zero_paid['MONTHLY_ORDER'] = non_zero_paid.groupby(['BILLING_PROVIDER_NPI_NUM','SERVICING_PROVIDER_NPI_NUM','HCPCS_CODE'])['CLAIM_FROM_MONTH'].rank(method='min', ascending=True)

non_zero_paid[(non_zero_paid['SERVICING_PROVIDER_NPI_NUM']=='1376609297') & (non_zero_paid['MONTHLY_ORDER'] == 1)].head() ## get the first month of claims for the given provider

first_month_paid_claims = non_zero_paid[(non_zero_paid['MONTHLY_ORDER'] == 1)].copy() ## get the first month of claims for the given provider

first_month_paid_claims.rename(columns={
    'CLAIM_FROM_MONTH_DATE':'FIRST_CLAIM_MONTH',
    'PAID_PER_CLAIM':'FIRST_PAID_PER_CLAIM'
}, inplace=True)

paid_per_claim_by_month_with_first_month = pd.merge(
    left=non_zero_paid,
    right=first_month_paid_claims[['BILLING_PROVIDER_NPI_NUM','SERVICING_PROVIDER_NPI_NUM','HCPCS_CODE','FIRST_CLAIM_MONTH','FIRST_PAID_PER_CLAIM']], ## to reduce resulting noise
    how='left',
    left_on=['BILLING_PROVIDER_NPI_NUM','SERVICING_PROVIDER_NPI_NUM','HCPCS_CODE'],
    right_on=['BILLING_PROVIDER_NPI_NUM','SERVICING_PROVIDER_NPI_NUM','HCPCS_CODE'],
)

paid_per_claim_by_month_with_first_month.head()

,BILLING_PROVIDER_NPI_NUM,SERVICING_PROVIDER_NPI_NUM,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIM_FROM_MONTH_DATE,CLAIM_YEAR,CLAIMS_PER_BENEFICIARY,PAID_PER_CLAIM,MONTHLY_ORDER,FIRST_CLAIM_MONTH,FIRST_PAID_PER_CLAIM
0,1376609297,1376609297,T1019,2024-07,39765,1205701,1.188877e+08,2024-07-01,2024,30.320659,98.604609,79.0,2018-01-01,88.29359
1,1376609297,1376609297,T1019,2024-08,39677,1152534,1.155611e+08,2024-08-01,2024,29.047912,100.266948,80.0,2018-01-01,88.29359
2,1376609297,1376609297,T1019,2024-05,39678,1157235,1.128233e+08,2024-05-01,2024,29.165659,97.493815,77.0,2018-01-01,88.29359
3,1376609297,1376609297,T1019,2024-06,39834,1164582,1.114492e+08,2024-06-01,2024,29.235879,95.698863,78.0,2018-01-01,88.29359
4,1376609297,1376609297,T1019,2024-09,39527,1099808,1.111998e+08,2024-09-01,2024,27.824221,101.108405,81.0,2018-01-01,88.29359

# Calculate Estimated Savings
- right now i have a default annual increase per HCPC of 5% on the paid/claim
- if you get paid 100/claim this year, next year you can earn at max 105
    - continually increasing costs will be the death of us
    - T1019 has doubled in price in 6 years for multiple providers
        - does it make sense to allow a code to double in what its paid out at?
        - shouldn't the government have more say in what they pay out per claim?
            - i understand risk plays a role, but i find it hard to justify doubling the cost per claim in 6 years

In [17]:
paid_per_claim_by_month_with_first_month.dropna(subset=['FIRST_CLAIM_MONTH', 'CLAIM_FROM_MONTH_DATE'], inplace=True)
paid_per_claim_by_month_with_first_month['PCT_CHANGE'] = paid_per_claim_by_month_with_first_month['PAID_PER_CLAIM'] / paid_per_claim_by_month_with_first_month['FIRST_PAID_PER_CLAIM']

paid_per_claim_by_month_with_first_month['MONTHS_SINCE_FIRST_PAID_CLAIM'] = (
    (paid_per_claim_by_month_with_first_month['CLAIM_FROM_MONTH_DATE'].dt.year - paid_per_claim_by_month_with_first_month['FIRST_CLAIM_MONTH'].dt.year) * 12 +
    (paid_per_claim_by_month_with_first_month['CLAIM_FROM_MONTH_DATE'].dt.month - paid_per_claim_by_month_with_first_month['FIRST_CLAIM_MONTH'].dt.month)
)

# assume 5% increase/year
annual_increase = 8

monthly_paid_per_claim_increase = pow(1+annual_increase/100, 1/12)

paid_per_claim_by_month_with_first_month['MONTHLY_CHANGE_RATE'] = paid_per_claim_by_month_with_first_month['PCT_CHANGE'] ** (1/paid_per_claim_by_month_with_first_month['MONTHS_SINCE_FIRST_PAID_CLAIM'])
paid_per_claim_by_month_with_first_month['ANNUALIZED_CHANGE_RATE'] = paid_per_claim_by_month_with_first_month['MONTHLY_CHANGE_RATE'] ** 12
ppc_col_nm = 'PAID_PER_CLAIM_'+str(annual_increase)+'_PCT_MONTHLY_INCREASE'
paid_per_claim_by_month_with_first_month[ppc_col_nm] = paid_per_claim_by_month_with_first_month['FIRST_PAID_PER_CLAIM'] * (monthly_paid_per_claim_increase ** paid_per_claim_by_month_with_first_month['MONTHS_SINCE_FIRST_PAID_CLAIM'])

# if the recalculated paid/claim is less than the given month's paid per claim, there are savings to be had
# covert T/F to use when adjusting savings calcs, if recalculated amount is higher, recoup savings

paid_per_claim_by_month_with_first_month['SAVINGS_INDICATOR'] = (paid_per_claim_by_month_with_first_month['PAID_PER_CLAIM'] > paid_per_claim_by_month_with_first_month['PAID_PER_CLAIM_5_PCT_MONTHLY_INCREASE']).astype(int)

paid_per_claim_by_month_with_first_month['SAVINGS_AMOUNT'] =  paid_per_claim_by_month_with_first_month['SAVINGS_INDICATOR'] * (paid_per_claim_by_month_with_first_month['PAID_PER_CLAIM'] - paid_per_claim_by_month_with_first_month[ppc_col_nm]) * paid_per_claim_by_month_with_first_month['TOTAL_CLAIMS']

In [21]:
paid_per_claim_by_month_with_first_month[paid_per_claim_by_month_with_first_month['SAVINGS_INDICATOR']==1].head(1000)

,BILLING_PROVIDER_NPI_NUM,SERVICING_PROVIDER_NPI_NUM,HCPCS_CODE,CLAIM_FROM_MONTH,TOTAL_UNIQUE_BENEFICIARIES,TOTAL_CLAIMS,TOTAL_PAID,CLAIM_FROM_MONTH_DATE,CLAIM_YEAR,CLAIMS_PER_BENEFICIARY,...,FIRST_CLAIM_MONTH,FIRST_PAID_PER_CLAIM,PCT_CHANGE,MONTHS_SINCE_FIRST_PAID_CLAIM,MONTHLY_CHANGE_RATE,ANNUALIZED_CHANGE_RATE,PAID_PER_CLAIM_5_PCT_MONTHLY_INCREASE,SAVINGS_INDICATOR,SAVINGS_AMOUNT,PAID_PER_CLAIM_8_PCT_MONTHLY_INCREASE
56,1417262056,1417262056,T1019,2024-09,34818,597907,55056558.57,2024-09-01,2024,17.172353,...,2018-01-01,44.480367,2.070175,80,1.009137,1.115324,61.578677,1,1.063160e+07,74.300784
58,1417262056,1417262056,T1019,2024-08,34690,599234,54781914.50,2024-08-01,2024,17.273969,...,2018-01-01,44.480367,2.055287,79,1.009161,1.115642,61.328816,1,1.054299e+07,73.825787
59,1417262056,1417262056,T1019,2024-07,34337,644264,54761232.80,2024-07-01,2024,18.762967,...,2018-01-01,44.480367,1.910913,78,1.008337,1.104760,61.079969,1,7.502003e+06,73.353826
60,1417262056,1417262056,T1019,2024-10,34486,590591,53809750.65,2024-10-01,2024,17.125529,...,2018-01-01,44.480367,2.048358,81,1.008892,1.112075,61.829557,1,9.646042e+06,74.778838
61,1417262056,1417262056,T1019,2024-05,33732,595379,53401322.33,2024-05-01,2024,17.650273,...,2018-01-01,44.480367,2.016462,76,1.009271,1.117103,60.585299,1,1.028461e+07,72.418937
63,1417262056,1417262056,T1019,2024-06,34074,581629,53250080.13,2024-06-01,2024,17.069584,...,2018-01-01,44.480367,2.058287,77,1.009419,1.119072,60.832131,1,1.085812e+07,72.884883
64,1417262056,1417262056,T1019,2024-01,33875,603803,52946668.11,2024-01-01,2024,17.824443,...,2018-01-01,44.480367,1.971401,72,1.009472,1.119771,59.607946,1,1.032738e+07,70.584752
66,1417262056,1417262056,T1019,2023-11,33363,597700,52417283.45,2023-11-01,2023,17.915056,...,2018-01-01,44.480367,1.971619,70,1.009745,1.123417,59.125198,1,1.076647e+07,69.685155
67,1417262056,1417262056,T1019,2023-10,33142,607495,52416359.25,2023-10-01,2023,18.330065,...,2018-01-01,44.480367,1.939795,69,1.009649,1.122133,58.885292,1,1.035361e+07,69.239665
68,1417262056,1417262056,T1019,2024-04,33504,597705,52277254.98,2024-04-01,2024,17.839810,...,2018-01-01,44.480367,1.966335,75,1.009056,1.114257,60.339469,1,9.268812e+06,71.955970
69,1417262056,1417262056,T1019,2024-02,33819,580015,52132534.47,2024-02-01,2024,17.150566,...,2018-01-01,44.480367,2.020697,73,1.009683,1.122585,59.850796,1,1.092891e+07,71.038897
70,1417262056,1417262056,T1019,2024-03,33071,601225,51473263.69,2024-03-01,2024,18.179825,...,2018-01-01,44.480367,1.924759,74,1.008888,1.112026,60.094636,1,8.488103e+06,71.495963
73,1417262056,1417262056,T1019,2023-09,32630,581215,50235951.33,2023-09-01,2023,17.812289,...,2018-01-01,44.480367,1.943164,68,1.009817,1.124381,58.646359,1,1.025009e+07,68.797023
76,1417262056,1417262056,T1019,2023-08,31728,575778,49046808.31,2023-08-01,2023,18.147315,...,2018-01-01,44.480367,1.915082,67,1.009745,1.123417,58.408396,1,9.688230e+06,68.357210
77,1417262056,1417262056,T1019,2023-07,31597,571180,48767700.55,2023-07-01,2023,18.077033,...,2018-01-01,44.480367,1.919512,66,1.009929,1.125873,58.171399,1,9.973035e+06,67.920210
78,1417262056,1417262056,T1019,2023-12,33331,547426,48729988.28,2023-12-01,2023,16.423930,...,2018-01-01,44.480367,2.001255,71,1.009819,1.124409,59.366081,1,1.033708e+07,70.133511
79,1417262056,1417262056,T1019,2023-06,31559,586553,48554673.73,2023-06-01,2023,18.585918,...,2018-01-01,44.480367,1.861039,65,1.009602,1.121504,57.935363,1,8.970556e+06,67.486003
80,1417262056,1417262056,T1019,2023-03,30828,578980,48047103.65,2023-03-01,2023,18.780978,...,2018-01-01,44.480367,1.865672,62,1.010109,1.128287,57.232986,1,9.718647e+06,66.199966
81,1417262056,1417262056,T1019,2023-05,30756,577903,48028831.56,2023-05-01,2023,18.789927,...,2018-01-01,44.480367,1.868438,64,1.009815,1.124352,57.700285,1,9.277793e+06,67.054572
82,1417262056,1417262056,T1019,2023-04,31068,568351,46853006.04,2023-04-01,2023,18.293775,...,2018-01-01,44.480367,1.853329,63,1.009841,1.124705,57.466161,1,8.986110e+06,66.625899
83,1417262056,1417262056,T1019,2023-02,30257,557742,46628399.56,2023-02-01,2023,18.433486,...,2018-01-01,44.480367,1.879528,61,1.010398,1.132169,57.000758,1,9.941940e+06,65.776756
85,1417262056,1417262056,T1019,2022-12,29808,558276,46125624.97,2022-12-01,2022,18.729066,...,2018-01-01,44.480367,1.857483,59,1.010551,1.134218,56.539125,1,9.872054e+06,64.938436
90,1417262056,1417262056,T1019,2022-11,29457,549751,45374745.42,2022-11-01,2022,18.662831,...,2018-01-01,44.480367,1.855581,58,1.010716,1.136443,56.309712,1,9.903001e+06,64.523292
91,1417262056,1417262056,T1019,2023-01,29982,571769,45310028.42,2023-01-01,2023,19.070409,...,2018-01-01,44.480367,1.781580,60,1.009671,1.122435,56.769472,1,7.941349e+06,65.356252
92,1417262056,1417262056,T1019,2022-10,29135,555342,45082618.49,2022-10-01,2022,19.060992,...,2018-01-01,44.480367,1.825073,57,1.010611,1.135027,56.081230,1,9.479198e+06,64.110801
97,1417262056,1417262056,T1019,2022-08,28481,553632,43723874.80,2022-08-01,2022,19.438643,...,2018-01-01,44.480367,1.775534,55,1.010493,1.133441,55.627044,1,8.682450e+06,63.293713
98,1417262056,1417262056,T1019,2022-09,28862,543161,43667639.44,2022-09-01,2022,18.819243,...,2018-01-01,44.480367,1.807435,56,1.010626,1.135233,55.853676,1,9.067769e+06,63.700947
100,1538649983,1538649983,S5126,2024-07,13350,378600,43324511.60,2024-07-01,2024,28.359551,...,2018-07-01,75.154286,1.522647,72,1.005857,1.072589,100.713931,1,-1.827478e+06,119.260406
101,1417262056,1417262056,T1019,2022-07,28363,546135,43191059.91,2022-07-01,2022,19.255192,...,2018-01-01,44.480367,1.777974,54,1.010714,1.136420,55.401332,1,8.845131e+06,62.889083
102,1417262056,1417262056,T1019,2022-06,28131,542912,42622382.50,2022-06-01,2022,19.299421,...,2018-01-01,44.480367,1.764981,53,1.010777,1.137275,55.176536,1,8.697419e+06,62.487040
103,1417262056,1417262056,T1019,2022-05,27841,570496,42202752.90,2022-05-01,2022,20.491218,...,2018-01-01,44.480367,1.663106,52,1.009830,1.124557,54.952652,1,6.782045e+06,62.087566
105,1538649983,1538649983,S5126,2024-08,13297,367196,41875055.00,2024-08-01,2024,27.614951,...,2018-07-01,75.154286,1.517413,73,1.005729,1.070953,101.124252,1,-2.198648e+06,120.027731
107,1417262056,1417262056,T1019,2022-04,27354,564384,41246624.32,2022-04-01,2022,20.632595,...,2018-01-01,44.480367,1.643029,51,1.009784,1.123932,54.729677,1,6.429410e+06,61.690647
109,1417262056,1417262056,T1019,2022-03,27051,555242,41197825.71,2022-03-01,2022,20.525748,...,2018-01-01,44.480367,1.668106,50,1.010286,1.130664,54.507606,1,7.163565e+06,61.296265
110,1538649983,1538649983,S5126,2024-05,13376,376598,41107189.23,2024-05-01,2024,28.154755,...,2018-07-01,75.154286,1.452399,70,1.005346,1.066071,99.898277,1,-3.233625e+06,117.740441
113,1538649983,1538649983,S5126,2024-01,13270,368329,40712412.04,2024-01-01,2024,27.756518,...,2018-07-01,75.154286,1.470744,66,1.005862,1.072658,98.286732,1,-1.556427e+06,114.758379
114,1538649983,1538649983,S5126,2024-10,13571,367311,40629255.26,2024-10-01,2024,27.065876,...,2018-07-01,75.154286,1.471808,75,1.005167,1.063791,101.949916,1,-4.027397e+06,121.577224
116,1538649983,1538649983,S5126,2024-06,13379,359649,40538340.85,2024-06-01,2024,26.881606,...,2018-07-01,75.154286,1.499800,71,1.005725,1.070908,100.305275,1,-2.079342e+06,118.497987
117,1538649983,1538649983,S5126,2024-03,13235,362811,40058665.84,2024-03-01,2024,27.412996,...,2018-07-01,75.154286,1.469137,68,1.005673,1.070241,99.089228,1,-2.114430e+06,116.239848
122,1538649983,1538649983,S5126,2024-09,13158,355554,39668820.86,2024-09-01,2024,27.021888,...,2018-07-01,75.154286,1.484533,74,1.005353,1.066167,101.536244,1,-3.282100e+06,120.799993
123,1538649983,1538649983,S5126,2024-04,13357,362766,39511503.88,2024-04-01,2024,27.159242,...,2018-07-01,75.154286,1.449250,69,1.005392,1.066657,99.492930,1,-2.927670e+06,116.987738
124,1417262056,1417262056,T1019,2022-02,26575,513850,39304560.12,2022-02-01,2022,19.335842,...,2018-01-01,44.480367,1.719643,49,1.011125,1.141980,54.286436,1,8.008832e+06,60.904404
128,1417262056,1417262056,T1019,2022-01,26406,534913,38879006.53,2022-01-01,2022,20.257252,...,2018-01-01,44.480367,1.634044,48,1.010283,1.130618,54.066164,1,6.508720e+06,60.515048
135,1538649983,1538649983,S5126,2023-12,13220,358185,38488013.32,2023-12-01,2023,27.094175,...,2018-07-01,75.154286,1.429764,65,1.005515,1.068229,97.887925,1,-2.353938e+06,114.024741
139,1417262056,1417262056,S5126,2021-07,12755,422445,38133702.93,2021-07-01,2021,33.119953,...,2018-01-01,66.740536,1.352537,42,1.007216,1.090112,79.168467,1,1.223791e+06,87.372112
140,1538649983,1538649983,S5126,2023-08,13227,360057,38099442.19,2023-08-01,2023,27.221365,...,2018-07-01,75.154286,1.407971,61,1.005625,1.069625,96.308811,1,-1.916136e+06,111.136788
142,1538649983,1538649983,S5126,2024-02,13241,347782,38050342.16,2024-02-01,2024,26.265539,...,2018-07-01,75.154286,1.455787,67,1.005621,1.069576,98.687165,1,-2.117344e+06,115.496738
143,1538649983,1538649983,S5126,2023-10,13260,363772,37991579.74,2023-10-01,2023,27.433786,...,2018-07-01,75.154286,1.389646,63,1.005237,1.064682,97.095158,1,-2.958781e+06,112.571504
147,1538649983,1538649983,S5126,2023-11,13245,352319,37025986.80,2023-11-01,2023,26.600151,...,2018-07-01,75.154286,1.398353,64,1.005253,1.064886,97.490735,1,-2.890273e+06,113.295792
148,1538649983,1538649983,S5126,2023-09,13210,351099,36926412.33,2023-09-01,2023,26.578274,...,2018-07-01,75.154286,1.399438,62,1.005435,1.067208,96.701185,1,-2.344659e+06,111.851846
157,1417262056,1417262056,S5126,2021-08,12757,406513,36138033.85,2021-08-01,2021,31.865878,...,2018-01-01,66.740536,1.331988,43,1.006689,1.083289,79.491009,1,3.916112e+05,87.934267
171,1417262056,1417262056,S5126,2021-09,12703,396140,35297688.45,2021-09-01,2021,31.184760,...,2018-01-01,66.740536,1.335082,44,1.006590,1.082005,79.814866,1,2.392831e+05,88.500039
172,1538649983,1538649983,S5126,2023-07,13125,321095,35134969.33,2023-07-01,2023,24.464381,...,2018-07-01,75.154286,1.455970,60,1.006281,1.078029,95.918029,1,-3.223641e+05,110.426302
173,1538649983,1538649983,S5126,2024-11,13175,308651,35108427.40,2024-11-01,2024,23.427021,...,2018-07-01,75.154286,1.513526,76,1.005468,1.067627,102.365272,1,-2.657941e+06,122.359456
179,1417262056,1417262056,S5126,2023-05,13919,330699,34075850.66,2023-05-01,2023,23.758819,...,2018-01-01,66.740536,1.543918,64,1.006809,1.084843,86.576353,1,8.035677e+05,100.611986
180,1417262056,1417262056,S5126,2021-05,12659,417609,34061124.06,2021-05-01,2021,32.989099,...,2018-01-01,66.740536,1.222079,40,1.005026,1.062013,78.527304,1,-1.961227e+06,86.258561
181,1376609297,1376609297,T1019,2018-03,17245,374227,33950896.46,2018-03-01,2018,21.700609,...,2018-01-01,88.293590,1.027512,2,1.013663,1.176852,89.014494,1,4.824988e+05,89.433413
183,1417262056,1417262056,S5126,2021-06,12737,413161,33824862.32,2021-06-01,2021,32.437858,...,2018-01-01,66.740536,1.226668,41,1.004995,1.061619,78.847234,1,-2.043111e+06,86.813551
184,1417262056,1417262056,S5126,2023-03,13810,329602,33799070.13,2023-03-01,2023,23.866908,...,2018-01-01,66.740536,1.536474,62,1.006951,1.086680,85.875195,1,1.059805e+06,99.329693
185,1417262056,1417262056,S5126,2023-06,13891,316919,33233492.86,2023-06-01,2023,22.814700,...,2018-01-01,66.740536,1.571224,65,1.006976,1.086998,86.929075,1,1.142488e+06,101.259326
188,1417262056,1417262056,S5126,2023-01,13631,318900,32768272.79,2023-01-01,2023,23.395202,...,2018-01-01,66.740536,1.539605,60,1.007218,1.090139,85.179716,1,1.495745e+06,98.063743
191,1417262056,1417262056,S5126,2022-12,13484,313552,32556432.78,2022-12-01,2022,23.253634,...,2018-01-01,66.740536,1.555742,59,1.007519,1.094052,84.834091,1,2.004919e+06,97.436832
195,1417262056,1417262056,T1019,2021-12,26099,503996,32128025.01,2021-12-01,2021,19.310931,...,2018-01-01,44.480367,1.433140,47,1.007686,1.096235,53.846786,1,1.823662e+06,60.128182
197,1417262056,1417262056,S5126,2023-04,13817,309177,32014082.50,2023-04-01,2023,22.376565,...,2018-01-01,66.740536,1.551473,63,1.006996,1.087257,86.225061,1,1.106034e+06,99.968783
198,1417262056,1417262056,T1019,2024-11,29019,336364,31843637.81,2024-11-01,2024,11.591164,...,2018-01-01,44.480367,2.128359,82,1.009254,1.116880,62.081458,1,6.528894e+06,75.259967
199,1417262056,1417262056,S5126,2022-08,13236,310160,31828617.47,2022-08-01,2022,23.433061,...,2018-01-01,66.740536,1.537596,55,1.007853,1.098413,83.465560,1,2.373030e+06,94.969008
200,1417262056,1417262056,S5126,2022-10,13415,309812,31758988.63,2022-10-01,2022,23.094447,...,2018-01-01,66.740536,1.535956,57,1.007557,1.094555,84.147043,1,1.956621e+06,96.195007
202,1417262056,1417262056,T1019,2021-10,25921,495550,31629319.98,2021-10-01,2021,19.117704,...,2018-01-01,44.480367,1.434941,45,1.008057,1.101089,53.410696,1,2.212554e+06,59.361853
203,1417262056,1417262056,T1019,2021-11,26165,484119,31589103.17,2021-11-01,2021,18.502542,...,2018-01-01,44.480367,1.466955,46,1.008365,1.105129,53.628297,1,2.666000e+06,59.743788
205,1417262056,1417262056,S5126,2022-11,13450,306476,31470668.31,2022-11-01,2022,22.786320,...,2018-01-01,66.740536,1.538579,58,1.007456,1.093237,84.489869,1,1.799523e+06,96.813928
206,1376609297,1376609297,T1019,2018-02,17234,338897,31443475.72,2018-02-01,2018,19.664442,...,2018-01-01,88.293590,1.050833,1,1.050833,1.813025,88.653309,1,1.328521e+06,88.861674
207,1417262056,1417262056,T1019,2021-08,25323,487933,31127465.87,2021-08-01,2021,19.268373,...,2018-01-01,44.480367,1.434218,43,1.008422,1.105876,52.978137,1,2.532011e+06,58.605290
208,1417262056,1417262056,S5126,2022-09,13286,303620,31029494.83,2022-09-01,2022,22.852627,...,2018-01-01,66.740536,1.531280,56,1.007638,1.095606,83.805609,1,2.009483e+06,95.580042
211,1417262056,1417262056,S5126,2022-07,13159,298986,30874136.09,2022-07-01,2022,22.721027,...,2018-01-01,66.740536,1.547228,54,1.008115,1.101852,83.126891,1,2.661255e+06,94.361881
212,1417262056,1417262056,T1019,2021-07,25045,486846,30856619.14,2021-07-01,2021,19.438850,...,2018-01-01,44.480367,1.424913,42,1.008467,1.106470,52.763174,1,2.507269e+06,58.230632
213,1538649983,1538649983,S5126,2023-03,9931,286432,30455869.78,2023-03-01,2023,28.842211,...,2018-07-01,75.154286,1.414802,56,1.006215,1.077189,94.370694,1,-3.726599e+05,107.629489
214,1417262056,1417262056,T1019,2021-09,25475,474716,30423618.43,2021-09-01,2021,18.634583,...,2018-01-01,44.480367,1.440816,44,1.008335,1.104732,53.193977,1,2.423749e+06,58.982358
216,1417262056,1417262056,S5126,2024-08,11149,266024,30336294.59,2024-08-01,2024,23.860795,...,2018-01-01,66.740536,1.708646,79,1.006804,1.084775,92.020780,1,8.683236e+05,110.771851
217,1417262056,1417262056,T1019,2021-05,24306,482358,30298061.88,2021-05-01,2021,19.845223,...,2018-01-01,44.480367,1.412138,40,1.008665,1.109081,52.335859,1,2.568030e+06,57.488487
219,1538649983,1538649983,S5126,2023-05,10052,284882,30213691.38,2023-05-01,2023,28.340828,...,2018-07-01,75.154286,1.411188,58,1.005956,1.073862,95.141216,1,-8.438386e+05,109.018927
221,1538649983,1538649983,S5126,2022-12,9767,273300,30208332.12,2022-12-01,2022,27.981980,...,2018-07-01,75.154286,1.470731,53,1.007305,1.091270,93.226595,1,1.353738e+06,105.578464
222,1538649983,1538649983,S5126,2023-01,9855,279840,30129251.07,2023-01-01,2023,28.395738,...,2018-07-01,75.154286,1.432599,54,1.006679,1.083164,93.606412,1,3.940799e+05,106.257759
223,1417262056,1417262056,S5126,2024-07,11083,264502,30124918.63,2024-07-01,2024,23.865560,...,2018-01-01,66.740536,1.706504,78,1.006875,1.085697,91.647397,1,1.012850e+06,110.063698
224,1538649983,1538649983,S5126,2023-06,10204,274642,30080675.48,2023-06-01,2023,26.915131,...,2018-07-01,75.154286,1.457360,59,1.006404,1.079612,95.528833,1,-5.314308e+04,109.720358
225,1417262056,1417262056,T1019,2021-06,24498,472683,30049083.45,2021-06-01,2021,19.294759,...,2018-01-01,44.480367,1.429200,41,1.008748,1.110179,52.549082,1,2.700416e+06,57.858370
226,1417262056,1417262056,T1019,2021-03,23860,487156,29936611.09,2021-03-01,2021,20.417267,...,2018-01-01,44.480367,1.381549,38,1.008542,1.107455,51.912006,1,2.287682e+06,56.755801
228,1417262056,1417262056,T1019,2021-04,24143,472074,29723820.13,2021-04-01,2021,19.553245,...,2018-01-01,44.480367,1.415553,39,1.008951,1.112856,52.123502,1,2.758496e+06,57.120969
231,1417262056,1417262056,S5126,2023-02,13674,289881,29625337.02,2023-02-01,2023,21.199430,...,2018-01-01,66.740536,1.531277,61,1.007010,1.087437,85.526748,1,1.015622e+06,98.694689
232,1417262056,1417262056,S5126,2024-10,11208,263538,29544159.82,2024-10-01,2024,23.513383,...,2018-01-01,66.740536,1.679727,81,1.006423,1.079863,92.772115,1,-2.529285e+04,112.201856
233,1538649983,1538649983,S5126,2022-10,9689,271732,29473309.29,2022-10-01,2022,28.045412,...,2018-07-01,75.154286,1.443226,51,1.007220,1.090160,92.471579,1,1.149902e+06,104.232874
234,1417262056,1417262056,S5126,2024-05,11083,266460,29332007.71,2024-05-01,2024,24.042227,...,2018-01-01,66.740536,1.649378,76,1.006606,1.082215,90.905170,1,3.782125e+05,108.660944
235,1538649983,1538649983,S5126,2023-04,9951,269673,29304505.19,2023-04-01,2023,27.100090,...,2018-07-01,75.154286,1.445916,57,1.006490,1.080723,94.755172,1,9.299186e+04,108.321980
236,1538649983,1538649983,S5126,2022-08,9528,267198,29241299.17,2022-08-01,2022,28.043451,...,2018-07-01,75.154286,1.456162,49,1.007699,1.096402,91.722677,1,1.745440e+06,102.904434
239,1417262056,1417262056,S5126,2022-03,13055,310768,29002969.00,2022-03-01,2022,23.804519,...,2018-01-01,66.740536,1.398352,50,1.006728,1.083797,81.785900,1,4.210337e+05,91.971938
240,1417262056,1417262056,S5126,2022-05,13133,308675,28979356.06,2022-05-01,2022,23.503769,...,2018-01-01,66.740536,1.406687,52,1.006584,1.081931,82.453669,1,2.234258e+05,93.159246
241,1417262056,1417262056,S5126,2024-01,10903,261403,28976251.07,2024-01-01,2024,23.975328,...,2018-01-01,66.740536,1.660894,72,1.007071,1.088237,89.438701,1,1.291362e+06,105.908843
242,1538649983,1538649983,S5126,2022-07,9385,256103,28811266.55,2022-07-01,2022,27.288546,...,2018-07-01,75.154286,1.496904,48,1.008440,1.106110,91.350504,1,2.625612e+06,102.246576
245,1538649983,1538649983,S5126,2022-11,9711,264424,28641365.92,2022-11-01,2022,27.229328,...,2018-07-01,75.154286,1.441249,52,1.007054,1.088008,92.848319,1,9.023598e+05,104.903511
246,1417262056,1417262056,T1019,2021-02,23101,449898,28614143.09,2021-02-01,2021,19.475261,...,2018-01-01,44.480367,1.429876,37,1.009711,1.122967,51.701368,1,3.243060e+06,56.392967
247,1417262056,1417262056,S5126,2024-03,11024,258736,28593816.64,2024-03-01,2024,23.470247,...,2018-01-01,66.740536,1.655867,74,1.006838,1.085220,90.168955,1,8.376358e+05,107.276069
249,1538649983,1538649983,S5126,2022-09,9621,264802,28522634.74,2022-09-01,2022,27.523334,...,2018-07-01,75.154286,1.433226,50,1.007225,1.090223,92.096367,1,1.098012e+06,103.566524
250,1417262056,1417262056,T1019,2021-01,22802,462588,28489030.28,2021-01-01,2021,20.287168,...,2018-01-01,44.480367,1.384570,36,1.009080,1.114564,51.491585,1,2.569090e+06,56.032452
251,1417262056,1417262056,S5126,2022-06,13200,299819,28430816.04,2022-06-01,2022,22.713561,...,2018-01-01,66.740536,1.420825,53,1.006649,1.082773,82.789596,1,3.201958e+05,93.758635
252,1417262056,1417262056,S5126,2024-09,11161,252562,28417375.56,2024-09-01,2024,22.628976,...,2018-01-01,66.740536,1.685878,80,1.006550,1.081494,92.395684,1,2.606119e+05,111.484561
254,1417262056,1417262056,S5126,2023-07,13517,267484,28379450.10,2023-07-01,2023,19.788711,...,2018-01-01,66.740536,1.589705,66,1.007048,1.087935,87.283235,1,1.119933e+06,101.910832
255,1417262056,1417262056,S5126,2021-12,12856,300608,28253601.84,2021-12-01,2021,23.382701,...,2018-01-01,66.740536,1.408262,47,1.007311,1.091344,80.794372,1,1.132962e+06,90.219289
256,1417262056,1417262056,T1019,2020-12,22653,465332,28190593.03,2020-12-01,2020,20.541738,...,2018-01-01,44.480367,1.361987,35,1.008866,1.111737,51.282653,1,2.283586e+06,55.674242

# Top savings by code

In [19]:
top_savings_by_code = paid_per_claim_by_month_with_first_month.groupby(['HCPCS_CODE']).agg(
    total_savings=('SAVINGS_AMOUNT','sum')
)

top_savings_by_code.sort_values(by='total_savings', ascending=False).head(100)

            total_savings
HCPCS_CODE
T1019        4.509863e+09
99213        3.301897e+09
99214        3.072360e+09
T1015        2.736077e+09
A0427        2.535499e+09
H2016        2.272946e+09
99284        2.144120e+09
99283        1.929981e+09
A0429        1.851665e+09
99285        1.769214e+09
T1020        1.525754e+09
T2016        1.295149e+09
H2015        1.225549e+09
T1016        1.077020e+09
S5125        1.015843e+09
H0020        9.933516e+08
90999        9.708551e+08
90837        9.584145e+08
S5130        8.978459e+08
H0004        8.817902e+08
H0019        8.779790e+08
G0463        8.695620e+08
H0018        7.950557e+08
H2014        7.909963e+08
H2017        7.719095e+08
H2019        7.492407e+08
H2036        7.290178e+08
T1017        6.673833e+08
T2023        6.112594e+08
T2031        5.715983e+08
97153        5.271634e+08
90834        4.977654e+08
T2033        4.879887e+08
97110        4.722167e+08
T2021        4.593435e+08
92507        4.444825e+08
99509        4.413987e+08
97530        4.344639e+08
S9124        3.939689e+08
U0003        3.677692e+08
T2046        3.442225e+08
A0100        3.434133e+08
H2022        3.277763e+08
H0036        3.161855e+08
S5102        2.356287e+08
S5140        1.822348e+08
T1000        1.584926e+08
T1040        8.225494e+07
00003        6.250913e+07
S5126       -9.574509e+04

# Top Savings by Provider

In [20]:
top_savings_by_billing_npi = paid_per_claim_by_month_with_first_month.groupby(['BILLING_PROVIDER_NPI_NUM']).agg(
    total_savings=('SAVINGS_AMOUNT','sum'),
    unique_codes=('HCPCS_CODE','nunique')
)

top_savings_by_billing_npi.sort_values(by='total_savings', ascending=False).head(100)

                          total_savings  unique_codes
BILLING_PROVIDER_NPI_NUM
1376554592                 1.072105e+09             2
1417262056                 4.334084e+08             5
1396049987                 3.779293e+08             7
1326111337                 2.974571e+08             4
1124494059                 2.913499e+08             1
1710176151                 2.753578e+08            11
1407897309                 2.572113e+08            14
1700090834                 2.103901e+08             7
1790835296                 1.780733e+08            12
1437156635                 1.759345e+08             6
1992805022                 1.516495e+08             2
1740339381                 1.372999e+08             4
1437175734                 1.362225e+08            14
1104253558                 1.358931e+08             3
1326502865                 1.261645e+08             6
1679525919                 1.216654e+08            13
1073854451                 1.137435e+08             3
1063436723                 1.097155e+08             8
1699703827                 1.094765e+08            12
1972655991                 1.005005e+08             1
1699725143                 9.416737e+07             3
1336117621                 9.139987e+07             3
1316158983                 8.854087e+07             6
1720145378                 8.758737e+07             9
1528263910                 8.593696e+07            11
1679524961                 8.090111e+07             4
1659402303                 8.072862e+07            12
1003213752                 7.647778e+07             1
1083789564                 7.258411e+07             2
1134152986                 7.227671e+07            15
1992886881                 7.170117e+07             3
1306801113                 7.087554e+07             2
1780630608                 6.882618e+07            13
1174649644                 6.791209e+07             5
1609953066                 6.470762e+07             1
1194934471                 6.439073e+07            14
1053821728                 6.409169e+07             3
1982757688                 6.348824e+07             9
1043488034                 6.228572e+07             1
1447261540                 6.112339e+07            14
1225255375                 6.102486e+07            11
1639131436                 6.101336e+07             2
1184703415                 5.718100e+07             4
1881777506                 5.623236e+07             6
1043386659                 5.524673e+07            10
1932570595                 5.445050e+07             2
1801131289                 5.431685e+07             2
1700120888                 5.381538e+07            12
1720050826                 5.341728e+07             2
1013093616                 5.311551e+07             4
1316943566                 5.309479e+07             2
1700828852                 5.258208e+07            15
1104963347                 5.243005e+07            12
1639172810                 5.214762e+07             9
1861506560                 5.184371e+07            13
1912510041                 5.170969e+07             3
1518012301                 5.113267e+07             6
1376600965                 5.075871e+07             2
1881061695                 5.065837e+07             5
1124595764                 5.008114e+07             1
1023788031                 5.002583e+07             4
1336290964                 4.912742e+07             2
1598898603                 4.851540e+07             3
1891010542                 4.797477e+07             8
1497257851                 4.784802e+07             1
1134260078                 4.710553e+07             1
1396051694                 4.665700e+07             3
1508124488                 4.638699e+07            12
1427531359                 4.630581e+07             2
1750304044                 4.611103e+07             2
1568407310                 4.577204e+07            14
1144384389                 4.513403e+07            11
1750823381                 4.488467e+07             1
1669878914                 4.463806e+07             2
1659315430                 4.451126e+07            10
1760472070                 4.397790e+07             2
1780621904                 4.360057e+07             8
1427138726                 4.359045e+07            13
1245446327                 4.333882e+07             1
1275665457                 4.291874e+07            11
1548496706                 4.167036e+07             8
1033165527                 4.161913e+07            10
1588157424                 4.141846e+07             4
1306068010                 4.117821e+07             5
1770538001                 4.112478e+07             9
1023174455                 4.074769e+07             7
1356496772                 4.048012e+07             6
1871538108                 4.047033e+07             4
1619969458                 4.033566e+07             8
1609961747                 3.934877e+07             3
1437125630                 3.914623e+07             1
1144420670                 3.904174e+07             2
1487603585                 3.879767e+07            14
1902032832                 3.864272e+07             8
1255868915                 3.803423e+07             1
1790835635                 3.790956e+07             1
1164543765                 3.786254e+07             4
1538195912                 3.731880e+07             6
1689769911                 3.719821e+07             9
1336119478                 3.719612e+07            12